// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: storage_service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	v1beta1 "github.com/kubescape/storage/pkg/apis/softwarecomposition/v1beta1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ErrorCode provides specific error types for programmatic handling
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED       ErrorCode = 0
	ErrorCode_ERROR_CODE_INVALID_REQUEST   ErrorCode = 1
	ErrorCode_ERROR_CODE_UNAUTHORIZED      ErrorCode = 2
	ErrorCode_ERROR_CODE_PROFILE_TOO_LARGE ErrorCode = 3
	ErrorCode_ERROR_CODE_PROFILE_COMPLETED ErrorCode = 4
	ErrorCode_ERROR_CODE_PROFILE_NOT_FOUND ErrorCode = 5
	ErrorCode_ERROR_CODE_INTERNAL_ERROR    ErrorCode = 6
	ErrorCode_ERROR_CODE_PULSAR_ERROR      ErrorCode = 7
)

var ErrorCode_name = map[int32]string{
	0: "ERROR_CODE_UNSPECIFIED",
	1: "ERROR_CODE_INVALID_REQUEST",
	2: "ERROR_CODE_UNAUTHORIZED",
	3: "ERROR_CODE_PROFILE_TOO_LARGE",
	4: "ERROR_CODE_PROFILE_COMPLETED",
	5: "ERROR_CODE_PROFILE_NOT_FOUND",
	6: "ERROR_CODE_INTERNAL_ERROR",
	7: "ERROR_CODE_PULSAR_ERROR",
}

var ErrorCode_value = map[string]int32{
	"ERROR_CODE_UNSPECIFIED":       0,
	"ERROR_CODE_INVALID_REQUEST":   1,
	"ERROR_CODE_UNAUTHORIZED":      2,
	"ERROR_CODE_PROFILE_TOO_LARGE": 3,
	"ERROR_CODE_PROFILE_COMPLETED": 4,
	"ERROR_CODE_PROFILE_NOT_FOUND": 5,
	"ERROR_CODE_INTERNAL_ERROR":    6,
	"ERROR_CODE_PULSAR_ERROR":      7,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{0}
}

// SendContainerProfileRequest contains the container profile to be stored
// customer_guid, cluster, host_type, and host_id are sent via gRPC metadata headers
type SendContainerProfileRequest struct {
	// ContainerProfile is the time-series container profile from node agent
	ContainerProfile     *v1beta1.ContainerProfile `protobuf:"bytes,1,opt,name=container_profile,json=containerProfile,proto3" json:"container_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *SendContainerProfileRequest) Reset()         { *m = SendContainerProfileRequest{} }
func (m *SendContainerProfileRequest) String() string { return proto.CompactTextString(m) }
func (*SendContainerProfileRequest) ProtoMessage()    {}
func (*SendContainerProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{0}
}
func (m *SendContainerProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendContainerProfileRequest.Unmarshal(m, b)
}
func (m *SendContainerProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendContainerProfileRequest.Marshal(b, m, deterministic)
}
func (m *SendContainerProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendContainerProfileRequest.Merge(m, src)
}
func (m *SendContainerProfileRequest) XXX_Size() int {
	return xxx_messageInfo_SendContainerProfileRequest.Size(m)
}
func (m *SendContainerProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendContainerProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendContainerProfileRequest proto.InternalMessageInfo

func (m *SendContainerProfileRequest) GetContainerProfile() *v1beta1.ContainerProfile {
	if m != nil {
		return m.ContainerProfile
	}
	return nil
}

// SendContainerProfileResponse indicates success or failure of the operation
type SendContainerProfileResponse struct {
	// Success indicates if the profile was successfully sent to Pulsar
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if the operation failed
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Error code for programmatic error handling
	ErrorCode            ErrorCode `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=storageserver.v1.ErrorCode" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SendContainerProfileResponse) Reset()         { *m = SendContainerProfileResponse{} }
func (m *SendContainerProfileResponse) String() string { return proto.CompactTextString(m) }
func (*SendContainerProfileResponse) ProtoMessage()    {}
func (*SendContainerProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{1}
}
func (m *SendContainerProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendContainerProfileResponse.Unmarshal(m, b)
}
func (m *SendContainerProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendContainerProfileResponse.Marshal(b, m, deterministic)
}
func (m *SendContainerProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendContainerProfileResponse.Merge(m, src)
}
func (m *SendContainerProfileResponse) XXX_Size() int {
	return xxx_messageInfo_SendContainerProfileResponse.Size(m)
}
func (m *SendContainerProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendContainerProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendContainerProfileResponse proto.InternalMessageInfo

func (m *SendContainerProfileResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SendContainerProfileResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *SendContainerProfileResponse) GetErrorCode() ErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

// GetProfileRequest requests an aggregated profile
// customer_guid, cluster, host_type, and host_id are sent via gRPC metadata headers
type GetProfileRequest struct {
	// Kind specifies the type of profile: "applicationProfile" or "networkNeighborhood"
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Namespace of the workload (k8s scope identifier)
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Name of the workload
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Region of the resource (non-k8s scope identifier, e.g. "us-east-1")
	Region string `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	// CloudAccountIdentifier of the resource (non-k8s scope identifier, e.g. AWS account ID "123456789012", GCP project ID)
	CloudAccountIdentifier string   `protobuf:"bytes,5,opt,name=cloud_account_identifier,json=cloudAccountIdentifier,proto3" json:"cloud_account_identifier,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *GetProfileRequest) Reset()         { *m = GetProfileRequest{} }
func (m *GetProfileRequest) String() string { return proto.CompactTextString(m) }
func (*GetProfileRequest) ProtoMessage()    {}
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{2}
}
func (m *GetProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfileRequest.Unmarshal(m, b)
}
func (m *GetProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfileRequest.Marshal(b, m, deterministic)
}
func (m *GetProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfileRequest.Merge(m, src)
}
func (m *GetProfileRequest) XXX_Size() int {
	return xxx_messageInfo_GetProfileRequest.Size(m)
}
func (m *GetProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfileRequest proto.InternalMessageInfo

func (m *GetProfileRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *GetProfileRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetProfileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetProfileRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *GetProfileRequest) GetCloudAccountIdentifier() string {
	if m != nil {
		return m.CloudAccountIdentifier
	}
	return ""
}

// GetProfileResponse contains the aggregated profile
type GetProfileResponse struct {
	// Success indicates if the profile was successfully retrieved
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if the operation failed
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Error code for programmatic error handling
	ErrorCode ErrorCode `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=storageserver.v1.ErrorCode" json:"error_code,omitempty"`
	// ApplicationProfile is populated when kind is "applicationProfile"
	ApplicationProfile *v1beta1.ApplicationProfile `protobuf:"bytes,4,opt,name=application_profile,json=applicationProfile,proto3" json:"application_profile,omitempty"`
	// NetworkNeighborhood is populated when kind is "networkNeighborhood"
	NetworkNeighborhood *v1beta1.NetworkNeighborhood `protobuf:"bytes,5,opt,name=network_neighborhood,json=networkNeighborhood,proto3" json:"network_neighborhood,omitempty"`
	// ContainerProfile is populated when kind is "containerProfile"
	ContainerProfile     *v1beta1.ContainerProfile `protobuf:"bytes,6,opt,name=container_profile,json=containerProfile,proto3" json:"container_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GetProfileResponse) Reset()         { *m = GetProfileResponse{} }
func (m *GetProfileResponse) String() string { return proto.CompactTextString(m) }
func (*GetProfileResponse) ProtoMessage()    {}
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{3}
}
func (m *GetProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfileResponse.Unmarshal(m, b)
}
func (m *GetProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfileResponse.Marshal(b, m, deterministic)
}
func (m *GetProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfileResponse.Merge(m, src)
}
func (m *GetProfileResponse) XXX_Size() int {
	return xxx_messageInfo_GetProfileResponse.Size(m)
}
func (m *GetProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfileResponse proto.InternalMessageInfo

func (m *GetProfileResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetProfileResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetProfileResponse) GetErrorCode() ErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (m *GetProfileResponse) GetApplicationProfile() *v1beta1.ApplicationProfile {
	if m != nil {
		return m.ApplicationProfile
	}
	return nil
}

func (m *GetProfileResponse) GetNetworkNeighborhood() *v1beta1.NetworkNeighborhood {
	if m != nil {
		return m.NetworkNeighborhood
	}
	return nil
}

func (m *GetProfileResponse) GetContainerProfile() *v1beta1.ContainerProfile {
	if m != nil {
		return m.ContainerProfile
	}
	return nil
}

// ListApplicationProfilesRequest requests a list of ApplicationProfiles in a namespace
// customer_guid, cluster, host_type, and host_id are sent via gRPC metadata headers
type ListApplicationProfilesRequest struct {
	// Namespace to list profiles from
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Limit number of items to return (0 means server default)
	Limit int64 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	// Continue token for pagination
	Cont string `protobuf:"bytes,5,opt,name=cont,proto3" json:"cont,omitempty"`
	// Region of the resource (non-k8s scope identifier, e.g. "us-east-1")
	Region string `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	// CloudAccountIdentifier of the resource (non-k8s scope identifier, e.g. AWS account ID "123456789012", GCP project ID)
	CloudAccountIdentifier string   `protobuf:"bytes,7,opt,name=cloud_account_identifier,json=cloudAccountIdentifier,proto3" json:"cloud_account_identifier,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *ListApplicationProfilesRequest) Reset()         { *m = ListApplicationProfilesRequest{} }
func (m *ListApplicationProfilesRequest) String() string { return proto.CompactTextString(m) }
func (*ListApplicationProfilesRequest) ProtoMessage()    {}
func (*ListApplicationProfilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{4}
}
func (m *ListApplicationProfilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListApplicationProfilesRequest.Unmarshal(m, b)
}
func (m *ListApplicationProfilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListApplicationProfilesRequest.Marshal(b, m, deterministic)
}
func (m *ListApplicationProfilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListApplicationProfilesRequest.Merge(m, src)
}
func (m *ListApplicationProfilesRequest) XXX_Size() int {
	return xxx_messageInfo_ListApplicationProfilesRequest.Size(m)
}
func (m *ListApplicationProfilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListApplicationProfilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListApplicationProfilesRequest proto.InternalMessageInfo

func (m *ListApplicationProfilesRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ListApplicationProfilesRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListApplicationProfilesRequest) GetCont() string {
	if m != nil {
		return m.Cont
	}
	return ""
}

func (m *ListApplicationProfilesRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *ListApplicationProfilesRequest) GetCloudAccountIdentifier() string {
	if m != nil {
		return m.CloudAccountIdentifier
	}
	return ""
}

// ListApplicationProfilesResponse contains the list of ApplicationProfiles (with nil Spec)
type ListApplicationProfilesResponse struct {
	// Success indicates if the list was successfully retrieved
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if the operation failed
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Error code for programmatic error handling
	ErrorCode ErrorCode `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=storageserver.v1.ErrorCode" json:"error_code,omitempty"`
	// ApplicationProfiles list (Spec will be nil for each item)
	ApplicationProfiles []*v1beta1.ApplicationProfile `protobuf:"bytes,4,rep,name=application_profiles,json=applicationProfiles,proto3" json:"application_profiles,omitempty"`
	// Continue token for next page (empty if no more results)
	Cont                 string   `protobuf:"bytes,5,opt,name=cont,proto3" json:"cont,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListApplicationProfilesResponse) Reset()         { *m = ListApplicationProfilesResponse{} }
func (m *ListApplicationProfilesResponse) String() string { return proto.CompactTextString(m) }
func (*ListApplicationProfilesResponse) ProtoMessage()    {}
func (*ListApplicationProfilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{5}
}
func (m *ListApplicationProfilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListApplicationProfilesResponse.Unmarshal(m, b)
}
func (m *ListApplicationProfilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListApplicationProfilesResponse.Marshal(b, m, deterministic)
}
func (m *ListApplicationProfilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListApplicationProfilesResponse.Merge(m, src)
}
func (m *ListApplicationProfilesResponse) XXX_Size() int {
	return xxx_messageInfo_ListApplicationProfilesResponse.Size(m)
}
func (m *ListApplicationProfilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListApplicationProfilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListApplicationProfilesResponse proto.InternalMessageInfo

func (m *ListApplicationProfilesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ListApplicationProfilesResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *ListApplicationProfilesResponse) GetErrorCode() ErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (m *ListApplicationProfilesResponse) GetApplicationProfiles() []*v1beta1.ApplicationProfile {
	if m != nil {
		return m.ApplicationProfiles
	}
	return nil
}

func (m *ListApplicationProfilesResponse) GetCont() string {
	if m != nil {
		return m.Cont
	}
	return ""
}

// ListNetworkNeighborhoodsRequest requests a list of NetworkNeighborhoods in a namespace
// customer_guid, cluster, host_type, and host_id are sent via gRPC metadata headers
type ListNetworkNeighborhoodsRequest struct {
	// Namespace to list neighborhoods from
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Limit number of items to return (0 means server default)
	Limit int64 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	// Continue token for pagination
	Cont string `protobuf:"bytes,5,opt,name=cont,proto3" json:"cont,omitempty"`
	// Region of the resource (non-k8s scope identifier, e.g. "us-east-1")
	Region string `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	// CloudAccountIdentifier of the resource (non-k8s scope identifier, e.g. AWS account ID "123456789012", GCP project ID)
	CloudAccountIdentifier string   `protobuf:"bytes,7,opt,name=cloud_account_identifier,json=cloudAccountIdentifier,proto3" json:"cloud_account_identifier,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *ListNetworkNeighborhoodsRequest) Reset()         { *m = ListNetworkNeighborhoodsRequest{} }
func (m *ListNetworkNeighborhoodsRequest) String() string { return proto.CompactTextString(m) }
func (*ListNetworkNeighborhoodsRequest) ProtoMessage()    {}
func (*ListNetworkNeighborhoodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{6}
}
func (m *ListNetworkNeighborhoodsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNetworkNeighborhoodsRequest.Unmarshal(m, b)
}
func (m *ListNetworkNeighborhoodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNetworkNeighborhoodsRequest.Marshal(b, m, deterministic)
}
func (m *ListNetworkNeighborhoodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNetworkNeighborhoodsRequest.Merge(m, src)
}
func (m *ListNetworkNeighborhoodsRequest) XXX_Size() int {
	return xxx_messageInfo_ListNetworkNeighborhoodsRequest.Size(m)
}
func (m *ListNetworkNeighborhoodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNetworkNeighborhoodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListNetworkNeighborhoodsRequest proto.InternalMessageInfo

func (m *ListNetworkNeighborhoodsRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ListNetworkNeighborhoodsRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListNetworkNeighborhoodsRequest) GetCont() string {
	if m != nil {
		return m.Cont
	}
	return ""
}

func (m *ListNetworkNeighborhoodsRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *ListNetworkNeighborhoodsRequest) GetCloudAccountIdentifier() string {
	if m != nil {
		return m.CloudAccountIdentifier
	}
	return ""
}

// ListNetworkNeighborhoodsResponse contains the list of NetworkNeighborhoods (with nil Spec)
type ListNetworkNeighborhoodsResponse struct {
	// Success indicates if the list was successfully retrieved
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if the operation failed
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Error code for programmatic error handling
	ErrorCode ErrorCode `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=storageserver.v1.ErrorCode" json:"error_code,omitempty"`
	// NetworkNeighborhoods list (Spec will be nil for each item)
	NetworkNeighborhoods []*v1beta1.NetworkNeighborhood `protobuf:"bytes,4,rep,name=network_neighborhoods,json=networkNeighborhoods,proto3" json:"network_neighborhoods,omitempty"`
	// Continue token for next page (empty if no more results)
	Cont                 string   `protobuf:"bytes,5,opt,name=cont,proto3" json:"cont,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListNetworkNeighborhoodsResponse) Reset()         { *m = ListNetworkNeighborhoodsResponse{} }
func (m *ListNetworkNeighborhoodsResponse) String() string { return proto.CompactTextString(m) }
func (*ListNetworkNeighborhoodsResponse) ProtoMessage()    {}
func (*ListNetworkNeighborhoodsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{7}
}
func (m *ListNetworkNeighborhoodsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNetworkNeighborhoodsResponse.Unmarshal(m, b)
}
func (m *ListNetworkNeighborhoodsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNetworkNeighborhoodsResponse.Marshal(b, m, deterministic)
}
func (m *ListNetworkNeighborhoodsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNetworkNeighborhoodsResponse.Merge(m, src)
}
func (m *ListNetworkNeighborhoodsResponse) XXX_Size() int {
	return xxx_messageInfo_ListNetworkNeighborhoodsResponse.Size(m)
}
func (m *ListNetworkNeighborhoodsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNetworkNeighborhoodsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListNetworkNeighborhoodsResponse proto.InternalMessageInfo

func (m *ListNetworkNeighborhoodsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ListNetworkNeighborhoodsResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *ListNetworkNeighborhoodsResponse) GetErrorCode() ErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (m *ListNetworkNeighborhoodsResponse) GetNetworkNeighborhoods() []*v1beta1.NetworkNeighborhood {
	if m != nil {
		return m.NetworkNeighborhoods
	}
	return nil
}

func (m *ListNetworkNeighborhoodsResponse) GetCont() string {
	if m != nil {
		return m.Cont
	}
	return ""
}

func init() {
	proto.RegisterEnum("storageserver.v1.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterType((*SendContainerProfileRequest)(nil), "storageserver.v1.SendContainerProfileRequest")
	proto.RegisterType((*SendContainerProfileResponse)(nil), "storageserver.v1.SendContainerProfileResponse")
	proto.RegisterType((*GetProfileRequest)(nil), "storageserver.v1.GetProfileRequest")
	proto.RegisterType((*GetProfileResponse)(nil), "storageserver.v1.GetProfileResponse")
	proto.RegisterType((*ListApplicationProfilesRequest)(nil), "storageserver.v1.ListApplicationProfilesRequest")
	proto.RegisterType((*ListApplicationProfilesResponse)(nil), "storageserver.v1.ListApplicationProfilesResponse")
	proto.RegisterType((*ListNetworkNeighborhoodsRequest)(nil), "storageserver.v1.ListNetworkNeighborhoodsRequest")
	proto.RegisterType((*ListNetworkNeighborhoodsResponse)(nil), "storageserver.v1.ListNetworkNeighborhoodsResponse")
}

func init() { proto.RegisterFile("storage_service.proto", fileDescriptor_3d90829bc66d9c54) }

var fileDescriptor_3d90829bc66d9c54 = []byte{
	// 856 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0x41, 0x8f, 0xda, 0x46,
	0x14, 0xae, 0x81, 0x65, 0xcb, 0x4b, 0x1b, 0x39, 0xb3, 0x64, 0xe3, 0xb2, 0xdb, 0x14, 0x91, 0x1e,
	0x56, 0x95, 0x6a, 0x07, 0x7a, 0xa9, 0x7a, 0xa3, 0xe0, 0x4d, 0x91, 0x08, 0x26, 0x03, 0xa4, 0x52,
	0x2e, 0x96, 0xb1, 0xdf, 0xb2, 0x23, 0xc0, 0xe3, 0x7a, 0xcc, 0xe6, 0x56, 0xb5, 0x97, 0xa8, 0x55,
	0x7f, 0x41, 0x6f, 0xbd, 0xf5, 0xd0, 0x7f, 0xd0, 0x1c, 0xfa, 0x67, 0xfa, 0x43, 0x2a, 0xc6, 0x66,
	0x97, 0xc5, 0x06, 0x25, 0x52, 0xb6, 0xab, 0x9c, 0x98, 0xf9, 0xde, 0x9b, 0x37, 0x1f, 0xef, 0x7d,
	0xf3, 0xfc, 0xe0, 0xbe, 0x88, 0x78, 0xe8, 0x4c, 0xd0, 0x16, 0x18, 0x5e, 0x30, 0x17, 0xf5, 0x20,
	0xe4, 0x11, 0x27, 0x6a, 0x02, 0x2f, 0x51, 0x0c, 0xf5, 0x8b, 0x7a, 0xe5, 0xd9, 0x84, 0x45, 0xe7,
	0x8b, 0xb1, 0xee, 0xf2, 0xb9, 0x31, 0x5d, 0x8c, 0x51, 0xb8, 0x4e, 0x80, 0x46, 0xe2, 0x66, 0x04,
	0xd3, 0x89, 0xe1, 0x04, 0x4c, 0x18, 0x82, 0x9f, 0x45, 0x2f, 0x9d, 0x10, 0x5d, 0x3e, 0x0f, 0xb8,
	0x60, 0x11, 0xe3, 0xbe, 0x71, 0x51, 0x1f, 0x63, 0xe4, 0xd4, 0x8d, 0x09, 0xfa, 0x18, 0x3a, 0x11,
	0x7a, 0xf1, 0x25, 0xb5, 0x3f, 0x14, 0x38, 0x1a, 0xa0, 0xef, 0xb5, 0xb8, 0x1f, 0x39, 0xcc, 0xc7,
	0xb0, 0x1f, 0xf2, 0x33, 0x36, 0x43, 0x8a, 0x3f, 0x2c, 0x50, 0x44, 0xe4, 0x27, 0x05, 0xee, 0xb9,
	0x2b, 0x9b, 0x1d, 0xc4, 0x46, 0x4d, 0xa9, 0x2a, 0x27, 0x77, 0x1a, 0x03, 0xfd, 0x8a, 0x8f, 0x7e,
	0xc9, 0x47, 0x4f, 0xf8, 0xe8, 0xc1, 0x74, 0xa2, 0x2f, 0xf9, 0xe8, 0x19, 0x7c, 0xf4, 0x84, 0x8f,
	0x9e, 0xba, 0x57, 0x75, 0x37, 0x90, 0xda, 0xef, 0x0a, 0x1c, 0x67, 0x53, 0x14, 0x01, 0xf7, 0x05,
	0x12, 0x0d, 0xf6, 0xc5, 0xc2, 0x75, 0x51, 0x08, 0x49, 0xec, 0x43, 0xba, 0xda, 0x92, 0x47, 0xf0,
	0x31, 0x86, 0x21, 0x0f, 0xed, 0x39, 0x0a, 0xe1, 0x4c, 0x50, 0xcb, 0x55, 0x95, 0x93, 0x12, 0xfd,
	0x48, 0x82, 0x4f, 0x63, 0x8c, 0x7c, 0x03, 0x10, 0x3b, 0xb9, 0xdc, 0x43, 0x2d, 0x5f, 0x55, 0x4e,
	0xee, 0x36, 0x8e, 0xf4, 0xcd, 0xe4, 0xeb, 0xe6, 0xd2, 0xa7, 0xc5, 0x3d, 0xa4, 0x25, 0x5c, 0x2d,
	0x6b, 0x7f, 0x29, 0x70, 0xef, 0x09, 0x46, 0x1b, 0x49, 0x23, 0x50, 0x98, 0x32, 0xdf, 0x93, 0x6c,
	0x4a, 0x54, 0xae, 0xc9, 0x31, 0x94, 0x7c, 0x67, 0x8e, 0x22, 0x70, 0xdc, 0x15, 0x8d, 0x2b, 0x60,
	0x79, 0x62, 0xb9, 0x91, 0xb7, 0x97, 0xa8, 0x5c, 0x93, 0x43, 0x28, 0x86, 0x38, 0x61, 0xdc, 0xd7,
	0x0a, 0x12, 0x4d, 0x76, 0xe4, 0x6b, 0xd0, 0xdc, 0x19, 0x5f, 0x78, 0xb6, 0xe3, 0xba, 0x7c, 0xe1,
	0x47, 0x36, 0xf3, 0xd0, 0x8f, 0xd8, 0x19, 0xc3, 0x50, 0xdb, 0x93, 0x9e, 0x87, 0xd2, 0xde, 0x8c,
	0xcd, 0x9d, 0x4b, 0x6b, 0xed, 0xcf, 0x02, 0x90, 0x75, 0xb6, 0xb7, 0x9e, 0x3f, 0xf2, 0x4a, 0x81,
	0x03, 0x27, 0x08, 0x66, 0xcc, 0x75, 0x96, 0xb2, 0xb8, 0x14, 0x58, 0x41, 0x0a, 0x6c, 0xf4, 0x0e,
	0x04, 0xd6, 0xbc, 0x8a, 0xbe, 0xfa, 0xdf, 0xc4, 0x49, 0x61, 0xe4, 0x57, 0x05, 0xca, 0x3e, 0x46,
	0x2f, 0x79, 0x38, 0xb5, 0x7d, 0x64, 0x93, 0xf3, 0x31, 0x0f, 0xcf, 0x39, 0xf7, 0x64, 0x46, 0xef,
	0x34, 0x9e, 0xbf, 0x03, 0x26, 0xbd, 0x38, 0x7c, 0x6f, 0x2d, 0x3a, 0x3d, 0xf0, 0xd3, 0xe0, 0x96,
	0x37, 0x57, 0xfc, 0x3f, 0xdf, 0xdc, 0xdf, 0x0a, 0x3c, 0xec, 0x32, 0x11, 0xa5, 0xb3, 0x27, 0x56,
	0x22, 0xbf, 0x26, 0x68, 0x65, 0x53, 0xd0, 0x65, 0xd8, 0x9b, 0xb1, 0x39, 0x8b, 0x64, 0x25, 0xf3,
	0x34, 0xde, 0x2c, 0x65, 0xbe, 0xbc, 0x2a, 0x91, 0xa9, 0x5c, 0xaf, 0xc9, 0xbc, 0xf8, 0xc6, 0x32,
	0xdf, 0xdf, 0x29, 0xf3, 0xd7, 0x39, 0xf8, 0x6c, 0x2b, 0xf9, 0xdb, 0xd7, 0xfc, 0x2f, 0x0a, 0x94,
	0x33, 0x34, 0x2f, 0xb4, 0x42, 0x35, 0x7f, 0x73, 0xa2, 0x3f, 0x48, 0x8b, 0x5e, 0x64, 0xd5, 0xa3,
	0xf6, 0x5a, 0x89, 0xb3, 0x97, 0x21, 0xd7, 0xf7, 0xa0, 0xf6, 0xff, 0xe4, 0xa0, 0xba, 0x9d, 0xfd,
	0xed, 0x17, 0xff, 0x37, 0x05, 0xee, 0x67, 0xf5, 0x99, 0x55, 0xf5, 0x6f, 0xaa, 0xd1, 0x94, 0x33,
	0x1a, 0x4d, 0x66, 0xfd, 0xbf, 0x78, 0x95, 0x83, 0xd2, 0x25, 0x75, 0x52, 0x81, 0x43, 0x93, 0x52,
	0x8b, 0xda, 0x2d, 0xab, 0x6d, 0xda, 0xa3, 0xde, 0xa0, 0x6f, 0xb6, 0x3a, 0xa7, 0x1d, 0xb3, 0xad,
	0x7e, 0x40, 0x1e, 0x42, 0x65, 0xcd, 0xd6, 0xe9, 0x3d, 0x6f, 0x76, 0x3b, 0x6d, 0x9b, 0x9a, 0xcf,
	0x46, 0xe6, 0x60, 0xa8, 0x2a, 0xe4, 0x08, 0x1e, 0x5c, 0x3b, 0xdb, 0x1c, 0x0d, 0xbf, 0xb3, 0x68,
	0xe7, 0x85, 0xd9, 0x56, 0x73, 0xa4, 0x0a, 0xc7, 0x6b, 0xc6, 0x3e, 0xb5, 0x4e, 0x3b, 0x5d, 0xd3,
	0x1e, 0x5a, 0x96, 0xdd, 0x6d, 0xd2, 0x27, 0xa6, 0x9a, 0xdf, 0xe2, 0xd1, 0xb2, 0x9e, 0xf6, 0xbb,
	0xe6, 0xd0, 0x6c, 0xab, 0x85, 0x2d, 0x1e, 0x3d, 0x6b, 0x68, 0x9f, 0x5a, 0xa3, 0x5e, 0x5b, 0xdd,
	0x23, 0x9f, 0xc2, 0x27, 0xd7, 0x28, 0x0e, 0x4d, 0xda, 0x6b, 0x76, 0x6d, 0x89, 0xa9, 0xc5, 0x0d,
	0x86, 0xfd, 0x51, 0x77, 0xd0, 0xa4, 0x89, 0x71, 0xbf, 0xf1, 0x6f, 0x1e, 0xee, 0x0e, 0xe2, 0xbc,
	0x0f, 0xe2, 0xc1, 0x8c, 0x2c, 0xa0, 0x9c, 0x35, 0x89, 0x90, 0x2f, 0xd3, 0xd5, 0xdf, 0x31, 0x54,
	0x55, 0xf4, 0x37, 0x75, 0x4f, 0xf4, 0xfa, 0x3d, 0xc0, 0xd5, 0x67, 0x9b, 0x3c, 0x4a, 0x9f, 0x4e,
	0x8d, 0x20, 0x95, 0xcf, 0x77, 0x3b, 0x25, 0x81, 0x7f, 0x84, 0x07, 0x5b, 0x1a, 0x25, 0x79, 0x9c,
	0x0e, 0xb0, 0xfb, 0x83, 0x50, 0xa9, 0xbf, 0xc5, 0x89, 0xe4, 0xfe, 0x9f, 0x15, 0xd0, 0xb6, 0xbd,
	0x56, 0xb2, 0x25, 0xde, 0x8e, 0xbe, 0x54, 0x69, 0xbc, 0xcd, 0x91, 0x98, 0xc3, 0xb7, 0x8d, 0x17,
	0x8f, 0x33, 0xc7, 0xea, 0xb1, 0xe3, 0x4e, 0xd1, 0xf7, 0xe4, 0x58, 0xed, 0xce, 0x18, 0xfa, 0x91,
	0x71, 0x51, 0x37, 0xe4, 0xd4, 0x3c, 0x2e, 0xca, 0x9f, 0xaf, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff,
	0x8b, 0xc1, 0x4a, 0xbf, 0xba, 0x0b, 0x00, 0x00,
}
