// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: storage_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageService_SendContainerProfile_FullMethodName       = "/storageserver.v1.StorageService/SendContainerProfile"
	StorageService_GetProfile_FullMethodName                 = "/storageserver.v1.StorageService/GetProfile"
	StorageService_ListApplicationProfiles_FullMethodName    = "/storageserver.v1.StorageService/ListApplicationProfiles"
	StorageService_ListNetworkNeighborhoods_FullMethodName   = "/storageserver.v1.StorageService/ListNetworkNeighborhoods"
	StorageService_SendContainerProfileStream_FullMethodName = "/storageserver.v1.StorageService/SendContainerProfileStream"
	StorageService_GetContainerProfileStream_FullMethodName  = "/storageserver.v1.StorageService/GetContainerProfileStream"
	StorageService_PutSBOMStream_FullMethodName              = "/storageserver.v1.StorageService/PutSBOMStream"
	StorageService_GetSBOMStream_FullMethodName              = "/storageserver.v1.StorageService/GetSBOMStream"
	StorageService_PatchSBOMAnnotations_FullMethodName       = "/storageserver.v1.StorageService/PatchSBOMAnnotations"
)

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StorageService provides gRPC endpoints for node agent to communicate with backend storage
type StorageServiceClient interface {
	// Deprecated: Do not use.
	// SendContainerProfile receives a container profile (time-series snapshot) from node agent
	// and sends it to Pulsar for processing by the ingester.
	//
	// Deprecated: use SendContainerProfileStream. The unary form is silently
	// capped by gRPC's default 4 MiB message limit; container profiles with
	// many or large entries (or with MaxContainerProfileSize raised) can
	// exceed this and fail on the wire. The streaming variant has no such
	// bound.
	SendContainerProfile(ctx context.Context, in *SendContainerProfileRequest, opts ...grpc.CallOption) (*SendContainerProfileResponse, error)
	// GetProfile retrieves an aggregated profile (ApplicationProfile, NetworkNeighborhood,
	// or ContainerProfile) by fetching them from S3.
	//
	// Note: for ContainerProfile specifically, prefer GetContainerProfileStream,
	// which is not subject to the default 4 MiB unary gRPC message limit.
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
	// ListApplicationProfiles lists all ApplicationProfiles in a namespace (returns metadata only, nil Spec)
	ListApplicationProfiles(ctx context.Context, in *ListApplicationProfilesRequest, opts ...grpc.CallOption) (*ListApplicationProfilesResponse, error)
	// ListNetworkNeighborhoods lists all NetworkNeighborhoods in a namespace (returns metadata only, nil Spec)
	ListNetworkNeighborhoods(ctx context.Context, in *ListNetworkNeighborhoodsRequest, opts ...grpc.CallOption) (*ListNetworkNeighborhoodsResponse, error)
	// SendContainerProfileStream is the streaming replacement for
	// SendContainerProfile. Client-streaming so the caller need not know the
	// payload size in advance — required because container profiles with
	// many or large entries can exceed the default 4 MiB unary gRPC limit.
	//
	// The first chunk MUST set metadata (which carries identifying labels
	// and may be empty otherwise) and MAY include blob_chunk for small
	// payloads. Subsequent chunks set only blob_chunk. Concatenated
	// blob_chunk values form the marshaled ContainerProfile proto payload.
	SendContainerProfileStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ContainerProfileChunk, SendContainerProfileResponse], error)
	// GetContainerProfileStream is the streaming replacement for
	// GetProfile(kind=ContainerProfile). Server-streaming so the caller need
	// not know the response size in advance.
	//
	// The first chunk in the response carries metadata + status. When the
	// profile does not exist or success is false, the server closes the
	// stream after the metadata chunk. Otherwise subsequent chunks carry
	// the marshaled ContainerProfile bytes.
	GetContainerProfileStream(ctx context.Context, in *GetContainerProfileStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetContainerProfileStreamChunk], error)
	// PutSBOMStream uploads an SBOM produced for an image. Client-streaming
	// so the caller need not know the payload size in advance and can stream
	// bytes from any io.Reader. Idempotent on (customer_guid, image_digest,
	// syft_version) — duplicate calls upsert the metadata row and overwrite
	// the S3 blob; end-state is consistent.
	//
	// The first chunk MUST set metadata (image_digest, syft_version, source)
	// and MAY include blob_chunk for small payloads. Subsequent chunks set
	// only blob_chunk. Concatenated blob_chunk values form the marshaled
	// SBOMSyft proto payload.
	PutSBOMStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutSBOMChunk, PutSBOMResponse], error)
	// GetSBOMStream probes for or fetches an SBOM by (customer_guid,
	// image_digest, syft_version). Server-streaming so the caller need not
	// know the response size in advance.
	//
	// The first chunk in the response carries metadata + status. When the
	// request sets metadata_only=true OR the row does not exist OR success
	// is false, the server closes the stream after the metadata chunk.
	// Otherwise subsequent chunks carry the marshaled SBOMSyft bytes.
	GetSBOMStream(ctx context.Context, in *GetSBOMRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetSBOMChunk], error)
	// PatchSBOMAnnotations updates only the annotations of an existing SBOM row,
	// atomically and without rewriting the blob. Merge-patch semantics: keys in
	// `set` are added or overwritten, keys in `delete` are removed, all other
	// annotations are left untouched. Not-found if the row does not exist.
	PatchSBOMAnnotations(ctx context.Context, in *PatchSBOMAnnotationsRequest, opts ...grpc.CallOption) (*PatchSBOMAnnotationsResponse, error)
}

type storageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageServiceClient(cc grpc.ClientConnInterface) StorageServiceClient {
	return &storageServiceClient{cc}
}

// Deprecated: Do not use.
func (c *storageServiceClient) SendContainerProfile(ctx context.Context, in *SendContainerProfileRequest, opts ...grpc.CallOption) (*SendContainerProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendContainerProfileResponse)
	err := c.cc.Invoke(ctx, StorageService_SendContainerProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, StorageService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ListApplicationProfiles(ctx context.Context, in *ListApplicationProfilesRequest, opts ...grpc.CallOption) (*ListApplicationProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListApplicationProfilesResponse)
	err := c.cc.Invoke(ctx, StorageService_ListApplicationProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ListNetworkNeighborhoods(ctx context.Context, in *ListNetworkNeighborhoodsRequest, opts ...grpc.CallOption) (*ListNetworkNeighborhoodsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNetworkNeighborhoodsResponse)
	err := c.cc.Invoke(ctx, StorageService_ListNetworkNeighborhoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) SendContainerProfileStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ContainerProfileChunk, SendContainerProfileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[0], StorageService_SendContainerProfileStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ContainerProfileChunk, SendContainerProfileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_SendContainerProfileStreamClient = grpc.ClientStreamingClient[ContainerProfileChunk, SendContainerProfileResponse]

func (c *storageServiceClient) GetContainerProfileStream(ctx context.Context, in *GetContainerProfileStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetContainerProfileStreamChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[1], StorageService_GetContainerProfileStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetContainerProfileStreamRequest, GetContainerProfileStreamChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_GetContainerProfileStreamClient = grpc.ServerStreamingClient[GetContainerProfileStreamChunk]

func (c *storageServiceClient) PutSBOMStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutSBOMChunk, PutSBOMResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[2], StorageService_PutSBOMStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PutSBOMChunk, PutSBOMResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_PutSBOMStreamClient = grpc.ClientStreamingClient[PutSBOMChunk, PutSBOMResponse]

func (c *storageServiceClient) GetSBOMStream(ctx context.Context, in *GetSBOMRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetSBOMChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[3], StorageService_GetSBOMStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetSBOMRequest, GetSBOMChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_GetSBOMStreamClient = grpc.ServerStreamingClient[GetSBOMChunk]

func (c *storageServiceClient) PatchSBOMAnnotations(ctx context.Context, in *PatchSBOMAnnotationsRequest, opts ...grpc.CallOption) (*PatchSBOMAnnotationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatchSBOMAnnotationsResponse)
	err := c.cc.Invoke(ctx, StorageService_PatchSBOMAnnotations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
// All implementations must embed UnimplementedStorageServiceServer
// for forward compatibility.
//
// StorageService provides gRPC endpoints for node agent to communicate with backend storage
type StorageServiceServer interface {
	// Deprecated: Do not use.
	// SendContainerProfile receives a container profile (time-series snapshot) from node agent
	// and sends it to Pulsar for processing by the ingester.
	//
	// Deprecated: use SendContainerProfileStream. The unary form is silently
	// capped by gRPC's default 4 MiB message limit; container profiles with
	// many or large entries (or with MaxContainerProfileSize raised) can
	// exceed this and fail on the wire. The streaming variant has no such
	// bound.
	SendContainerProfile(context.Context, *SendContainerProfileRequest) (*SendContainerProfileResponse, error)
	// GetProfile retrieves an aggregated profile (ApplicationProfile, NetworkNeighborhood,
	// or ContainerProfile) by fetching them from S3.
	//
	// Note: for ContainerProfile specifically, prefer GetContainerProfileStream,
	// which is not subject to the default 4 MiB unary gRPC message limit.
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	// ListApplicationProfiles lists all ApplicationProfiles in a namespace (returns metadata only, nil Spec)
	ListApplicationProfiles(context.Context, *ListApplicationProfilesRequest) (*ListApplicationProfilesResponse, error)
	// ListNetworkNeighborhoods lists all NetworkNeighborhoods in a namespace (returns metadata only, nil Spec)
	ListNetworkNeighborhoods(context.Context, *ListNetworkNeighborhoodsRequest) (*ListNetworkNeighborhoodsResponse, error)
	// SendContainerProfileStream is the streaming replacement for
	// SendContainerProfile. Client-streaming so the caller need not know the
	// payload size in advance — required because container profiles with
	// many or large entries can exceed the default 4 MiB unary gRPC limit.
	//
	// The first chunk MUST set metadata (which carries identifying labels
	// and may be empty otherwise) and MAY include blob_chunk for small
	// payloads. Subsequent chunks set only blob_chunk. Concatenated
	// blob_chunk values form the marshaled ContainerProfile proto payload.
	SendContainerProfileStream(grpc.ClientStreamingServer[ContainerProfileChunk, SendContainerProfileResponse]) error
	// GetContainerProfileStream is the streaming replacement for
	// GetProfile(kind=ContainerProfile). Server-streaming so the caller need
	// not know the response size in advance.
	//
	// The first chunk in the response carries metadata + status. When the
	// profile does not exist or success is false, the server closes the
	// stream after the metadata chunk. Otherwise subsequent chunks carry
	// the marshaled ContainerProfile bytes.
	GetContainerProfileStream(*GetContainerProfileStreamRequest, grpc.ServerStreamingServer[GetContainerProfileStreamChunk]) error
	// PutSBOMStream uploads an SBOM produced for an image. Client-streaming
	// so the caller need not know the payload size in advance and can stream
	// bytes from any io.Reader. Idempotent on (customer_guid, image_digest,
	// syft_version) — duplicate calls upsert the metadata row and overwrite
	// the S3 blob; end-state is consistent.
	//
	// The first chunk MUST set metadata (image_digest, syft_version, source)
	// and MAY include blob_chunk for small payloads. Subsequent chunks set
	// only blob_chunk. Concatenated blob_chunk values form the marshaled
	// SBOMSyft proto payload.
	PutSBOMStream(grpc.ClientStreamingServer[PutSBOMChunk, PutSBOMResponse]) error
	// GetSBOMStream probes for or fetches an SBOM by (customer_guid,
	// image_digest, syft_version). Server-streaming so the caller need not
	// know the response size in advance.
	//
	// The first chunk in the response carries metadata + status. When the
	// request sets metadata_only=true OR the row does not exist OR success
	// is false, the server closes the stream after the metadata chunk.
	// Otherwise subsequent chunks carry the marshaled SBOMSyft bytes.
	GetSBOMStream(*GetSBOMRequest, grpc.ServerStreamingServer[GetSBOMChunk]) error
	// PatchSBOMAnnotations updates only the annotations of an existing SBOM row,
	// atomically and without rewriting the blob. Merge-patch semantics: keys in
	// `set` are added or overwritten, keys in `delete` are removed, all other
	// annotations are left untouched. Not-found if the row does not exist.
	PatchSBOMAnnotations(context.Context, *PatchSBOMAnnotationsRequest) (*PatchSBOMAnnotationsResponse, error)
	mustEmbedUnimplementedStorageServiceServer()
}

// UnimplementedStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageServiceServer struct{}

func (UnimplementedStorageServiceServer) SendContainerProfile(context.Context, *SendContainerProfileRequest) (*SendContainerProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendContainerProfile not implemented")
}
func (UnimplementedStorageServiceServer) GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedStorageServiceServer) ListApplicationProfiles(context.Context, *ListApplicationProfilesRequest) (*ListApplicationProfilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListApplicationProfiles not implemented")
}
func (UnimplementedStorageServiceServer) ListNetworkNeighborhoods(context.Context, *ListNetworkNeighborhoodsRequest) (*ListNetworkNeighborhoodsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNetworkNeighborhoods not implemented")
}
func (UnimplementedStorageServiceServer) SendContainerProfileStream(grpc.ClientStreamingServer[ContainerProfileChunk, SendContainerProfileResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SendContainerProfileStream not implemented")
}
func (UnimplementedStorageServiceServer) GetContainerProfileStream(*GetContainerProfileStreamRequest, grpc.ServerStreamingServer[GetContainerProfileStreamChunk]) error {
	return status.Errorf(codes.Unimplemented, "method GetContainerProfileStream not implemented")
}
func (UnimplementedStorageServiceServer) PutSBOMStream(grpc.ClientStreamingServer[PutSBOMChunk, PutSBOMResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PutSBOMStream not implemented")
}
func (UnimplementedStorageServiceServer) GetSBOMStream(*GetSBOMRequest, grpc.ServerStreamingServer[GetSBOMChunk]) error {
	return status.Errorf(codes.Unimplemented, "method GetSBOMStream not implemented")
}
func (UnimplementedStorageServiceServer) PatchSBOMAnnotations(context.Context, *PatchSBOMAnnotationsRequest) (*PatchSBOMAnnotationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchSBOMAnnotations not implemented")
}
func (UnimplementedStorageServiceServer) mustEmbedUnimplementedStorageServiceServer() {}
func (UnimplementedStorageServiceServer) testEmbeddedByValue()                        {}

// UnsafeStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServiceServer will
// result in compilation errors.
type UnsafeStorageServiceServer interface {
	mustEmbedUnimplementedStorageServiceServer()
}

func RegisterStorageServiceServer(s grpc.ServiceRegistrar, srv StorageServiceServer) {
	// If the following call pancis, it indicates UnimplementedStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageService_ServiceDesc, srv)
}

func _StorageService_SendContainerProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendContainerProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).SendContainerProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_SendContainerProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).SendContainerProfile(ctx, req.(*SendContainerProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ListApplicationProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplicationProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ListApplicationProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_ListApplicationProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ListApplicationProfiles(ctx, req.(*ListApplicationProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ListNetworkNeighborhoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNetworkNeighborhoodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ListNetworkNeighborhoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_ListNetworkNeighborhoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ListNetworkNeighborhoods(ctx, req.(*ListNetworkNeighborhoodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_SendContainerProfileStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorageServiceServer).SendContainerProfileStream(&grpc.GenericServerStream[ContainerProfileChunk, SendContainerProfileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_SendContainerProfileStreamServer = grpc.ClientStreamingServer[ContainerProfileChunk, SendContainerProfileResponse]

func _StorageService_GetContainerProfileStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetContainerProfileStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServiceServer).GetContainerProfileStream(m, &grpc.GenericServerStream[GetContainerProfileStreamRequest, GetContainerProfileStreamChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_GetContainerProfileStreamServer = grpc.ServerStreamingServer[GetContainerProfileStreamChunk]

func _StorageService_PutSBOMStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorageServiceServer).PutSBOMStream(&grpc.GenericServerStream[PutSBOMChunk, PutSBOMResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_PutSBOMStreamServer = grpc.ClientStreamingServer[PutSBOMChunk, PutSBOMResponse]

func _StorageService_GetSBOMStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetSBOMRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServiceServer).GetSBOMStream(m, &grpc.GenericServerStream[GetSBOMRequest, GetSBOMChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_GetSBOMStreamServer = grpc.ServerStreamingServer[GetSBOMChunk]

func _StorageService_PatchSBOMAnnotations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchSBOMAnnotationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).PatchSBOMAnnotations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_PatchSBOMAnnotations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).PatchSBOMAnnotations(ctx, req.(*PatchSBOMAnnotationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageService_ServiceDesc is the grpc.ServiceDesc for StorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storageserver.v1.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendContainerProfile",
			Handler:    _StorageService_SendContainerProfile_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _StorageService_GetProfile_Handler,
		},
		{
			MethodName: "ListApplicationProfiles",
			Handler:    _StorageService_ListApplicationProfiles_Handler,
		},
		{
			MethodName: "ListNetworkNeighborhoods",
			Handler:    _StorageService_ListNetworkNeighborhoods_Handler,
		},
		{
			MethodName: "PatchSBOMAnnotations",
			Handler:    _StorageService_PatchSBOMAnnotations_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendContainerProfileStream",
			Handler:       _StorageService_SendContainerProfileStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetContainerProfileStream",
			Handler:       _StorageService_GetContainerProfileStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PutSBOMStream",
			Handler:       _StorageService_PutSBOMStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetSBOMStream",
			Handler:       _StorageService_GetSBOMStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "storage_service.proto",
}
