// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: storage_service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	v1beta1 "github.com/kubescape/storage/pkg/apis/softwarecomposition/v1beta1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ErrorCode provides specific error types for programmatic handling
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED       ErrorCode = 0
	ErrorCode_ERROR_CODE_INVALID_REQUEST   ErrorCode = 1
	ErrorCode_ERROR_CODE_UNAUTHORIZED      ErrorCode = 2
	ErrorCode_ERROR_CODE_PROFILE_TOO_LARGE ErrorCode = 3
	ErrorCode_ERROR_CODE_PROFILE_COMPLETED ErrorCode = 4
	ErrorCode_ERROR_CODE_PROFILE_NOT_FOUND ErrorCode = 5
	ErrorCode_ERROR_CODE_INTERNAL_ERROR    ErrorCode = 6
	ErrorCode_ERROR_CODE_PULSAR_ERROR      ErrorCode = 7
	ErrorCode_ERROR_CODE_SBOM_NOT_FOUND    ErrorCode = 8
	ErrorCode_ERROR_CODE_SBOM_TOO_LARGE    ErrorCode = 9
)

var ErrorCode_name = map[int32]string{
	0: "ERROR_CODE_UNSPECIFIED",
	1: "ERROR_CODE_INVALID_REQUEST",
	2: "ERROR_CODE_UNAUTHORIZED",
	3: "ERROR_CODE_PROFILE_TOO_LARGE",
	4: "ERROR_CODE_PROFILE_COMPLETED",
	5: "ERROR_CODE_PROFILE_NOT_FOUND",
	6: "ERROR_CODE_INTERNAL_ERROR",
	7: "ERROR_CODE_PULSAR_ERROR",
	8: "ERROR_CODE_SBOM_NOT_FOUND",
	9: "ERROR_CODE_SBOM_TOO_LARGE",
}

var ErrorCode_value = map[string]int32{
	"ERROR_CODE_UNSPECIFIED":       0,
	"ERROR_CODE_INVALID_REQUEST":   1,
	"ERROR_CODE_UNAUTHORIZED":      2,
	"ERROR_CODE_PROFILE_TOO_LARGE": 3,
	"ERROR_CODE_PROFILE_COMPLETED": 4,
	"ERROR_CODE_PROFILE_NOT_FOUND": 5,
	"ERROR_CODE_INTERNAL_ERROR":    6,
	"ERROR_CODE_PULSAR_ERROR":      7,
	"ERROR_CODE_SBOM_NOT_FOUND":    8,
	"ERROR_CODE_SBOM_TOO_LARGE":    9,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{0}
}

// SBOMSource identifies how an SBOM entered the backend.
type SBOMSource int32

const (
	SBOMSource_SBOM_SOURCE_UNSPECIFIED SBOMSource = 0
	// SBOM_SOURCE_WORKLOAD: generated by node-agent for an in-cluster workload image.
	SBOMSource_SBOM_SOURCE_WORKLOAD SBOMSource = 1
	// SBOM_SOURCE_REGISTRY: generated by kubevuln for a registry image (Registry Epic).
	SBOMSource_SBOM_SOURCE_REGISTRY SBOMSource = 2
	// SBOM_SOURCE_HOST: generated by the host scanner for an EC2 host snapshot.
	SBOMSource_SBOM_SOURCE_HOST SBOMSource = 3
)

var SBOMSource_name = map[int32]string{
	0: "SBOM_SOURCE_UNSPECIFIED",
	1: "SBOM_SOURCE_WORKLOAD",
	2: "SBOM_SOURCE_REGISTRY",
	3: "SBOM_SOURCE_HOST",
}

var SBOMSource_value = map[string]int32{
	"SBOM_SOURCE_UNSPECIFIED": 0,
	"SBOM_SOURCE_WORKLOAD":    1,
	"SBOM_SOURCE_REGISTRY":    2,
	"SBOM_SOURCE_HOST":        3,
}

func (x SBOMSource) String() string {
	return proto.EnumName(SBOMSource_name, int32(x))
}

func (SBOMSource) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{1}
}

// SendContainerProfileRequest contains the container profile to be stored
// customer_guid, cluster, host_type, and host_id are sent via gRPC metadata headers
type SendContainerProfileRequest struct {
	// ContainerProfile is the time-series container profile from node agent
	ContainerProfile     *v1beta1.ContainerProfile `protobuf:"bytes,1,opt,name=container_profile,json=containerProfile,proto3" json:"container_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *SendContainerProfileRequest) Reset()         { *m = SendContainerProfileRequest{} }
func (m *SendContainerProfileRequest) String() string { return proto.CompactTextString(m) }
func (*SendContainerProfileRequest) ProtoMessage()    {}
func (*SendContainerProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{0}
}
func (m *SendContainerProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendContainerProfileRequest.Unmarshal(m, b)
}
func (m *SendContainerProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendContainerProfileRequest.Marshal(b, m, deterministic)
}
func (m *SendContainerProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendContainerProfileRequest.Merge(m, src)
}
func (m *SendContainerProfileRequest) XXX_Size() int {
	return xxx_messageInfo_SendContainerProfileRequest.Size(m)
}
func (m *SendContainerProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendContainerProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendContainerProfileRequest proto.InternalMessageInfo

func (m *SendContainerProfileRequest) GetContainerProfile() *v1beta1.ContainerProfile {
	if m != nil {
		return m.ContainerProfile
	}
	return nil
}

// SendContainerProfileResponse indicates success or failure of the operation
type SendContainerProfileResponse struct {
	// Success indicates if the profile was successfully sent to Pulsar
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if the operation failed
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Error code for programmatic error handling
	ErrorCode            ErrorCode `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=storageserver.v1.ErrorCode" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SendContainerProfileResponse) Reset()         { *m = SendContainerProfileResponse{} }
func (m *SendContainerProfileResponse) String() string { return proto.CompactTextString(m) }
func (*SendContainerProfileResponse) ProtoMessage()    {}
func (*SendContainerProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{1}
}
func (m *SendContainerProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendContainerProfileResponse.Unmarshal(m, b)
}
func (m *SendContainerProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendContainerProfileResponse.Marshal(b, m, deterministic)
}
func (m *SendContainerProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendContainerProfileResponse.Merge(m, src)
}
func (m *SendContainerProfileResponse) XXX_Size() int {
	return xxx_messageInfo_SendContainerProfileResponse.Size(m)
}
func (m *SendContainerProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendContainerProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendContainerProfileResponse proto.InternalMessageInfo

func (m *SendContainerProfileResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SendContainerProfileResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *SendContainerProfileResponse) GetErrorCode() ErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

// GetProfileRequest requests an aggregated profile
// customer_guid, cluster, host_type, and host_id are sent via gRPC metadata headers
type GetProfileRequest struct {
	// Kind specifies the type of profile: "applicationProfile", "networkNeighborhood", or "containerProfile"
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Namespace of the workload (k8s scope identifier)
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Name of the workload
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Region of the resource (non-k8s scope identifier, e.g. "us-east-1")
	Region string `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	// CloudAccountIdentifier of the resource (non-k8s scope identifier, e.g. AWS account ID "123456789012", GCP project ID)
	CloudAccountIdentifier string   `protobuf:"bytes,5,opt,name=cloud_account_identifier,json=cloudAccountIdentifier,proto3" json:"cloud_account_identifier,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *GetProfileRequest) Reset()         { *m = GetProfileRequest{} }
func (m *GetProfileRequest) String() string { return proto.CompactTextString(m) }
func (*GetProfileRequest) ProtoMessage()    {}
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{2}
}
func (m *GetProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfileRequest.Unmarshal(m, b)
}
func (m *GetProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfileRequest.Marshal(b, m, deterministic)
}
func (m *GetProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfileRequest.Merge(m, src)
}
func (m *GetProfileRequest) XXX_Size() int {
	return xxx_messageInfo_GetProfileRequest.Size(m)
}
func (m *GetProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfileRequest proto.InternalMessageInfo

func (m *GetProfileRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *GetProfileRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetProfileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetProfileRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *GetProfileRequest) GetCloudAccountIdentifier() string {
	if m != nil {
		return m.CloudAccountIdentifier
	}
	return ""
}

// GetProfileResponse contains the aggregated profile
type GetProfileResponse struct {
	// Success indicates if the profile was successfully retrieved
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if the operation failed
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Error code for programmatic error handling
	ErrorCode ErrorCode `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=storageserver.v1.ErrorCode" json:"error_code,omitempty"`
	// ApplicationProfile is populated when kind is "applicationProfile"
	ApplicationProfile *v1beta1.ApplicationProfile `protobuf:"bytes,4,opt,name=application_profile,json=applicationProfile,proto3" json:"application_profile,omitempty"`
	// NetworkNeighborhood is populated when kind is "networkNeighborhood"
	NetworkNeighborhood *v1beta1.NetworkNeighborhood `protobuf:"bytes,5,opt,name=network_neighborhood,json=networkNeighborhood,proto3" json:"network_neighborhood,omitempty"`
	// ContainerProfile is populated when kind is "containerProfile"
	ContainerProfile     *v1beta1.ContainerProfile `protobuf:"bytes,6,opt,name=container_profile,json=containerProfile,proto3" json:"container_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GetProfileResponse) Reset()         { *m = GetProfileResponse{} }
func (m *GetProfileResponse) String() string { return proto.CompactTextString(m) }
func (*GetProfileResponse) ProtoMessage()    {}
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{3}
}
func (m *GetProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfileResponse.Unmarshal(m, b)
}
func (m *GetProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfileResponse.Marshal(b, m, deterministic)
}
func (m *GetProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfileResponse.Merge(m, src)
}
func (m *GetProfileResponse) XXX_Size() int {
	return xxx_messageInfo_GetProfileResponse.Size(m)
}
func (m *GetProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfileResponse proto.InternalMessageInfo

func (m *GetProfileResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetProfileResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetProfileResponse) GetErrorCode() ErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (m *GetProfileResponse) GetApplicationProfile() *v1beta1.ApplicationProfile {
	if m != nil {
		return m.ApplicationProfile
	}
	return nil
}

func (m *GetProfileResponse) GetNetworkNeighborhood() *v1beta1.NetworkNeighborhood {
	if m != nil {
		return m.NetworkNeighborhood
	}
	return nil
}

func (m *GetProfileResponse) GetContainerProfile() *v1beta1.ContainerProfile {
	if m != nil {
		return m.ContainerProfile
	}
	return nil
}

// ListApplicationProfilesRequest requests a list of ApplicationProfiles in a namespace
// customer_guid, cluster, host_type, and host_id are sent via gRPC metadata headers
type ListApplicationProfilesRequest struct {
	// Namespace to list profiles from
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Limit number of items to return (0 means server default)
	Limit int64 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	// Continue token for pagination
	Cont string `protobuf:"bytes,5,opt,name=cont,proto3" json:"cont,omitempty"`
	// Region of the resource (non-k8s scope identifier, e.g. "us-east-1")
	Region string `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	// CloudAccountIdentifier of the resource (non-k8s scope identifier, e.g. AWS account ID "123456789012", GCP project ID)
	CloudAccountIdentifier string   `protobuf:"bytes,7,opt,name=cloud_account_identifier,json=cloudAccountIdentifier,proto3" json:"cloud_account_identifier,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *ListApplicationProfilesRequest) Reset()         { *m = ListApplicationProfilesRequest{} }
func (m *ListApplicationProfilesRequest) String() string { return proto.CompactTextString(m) }
func (*ListApplicationProfilesRequest) ProtoMessage()    {}
func (*ListApplicationProfilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{4}
}
func (m *ListApplicationProfilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListApplicationProfilesRequest.Unmarshal(m, b)
}
func (m *ListApplicationProfilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListApplicationProfilesRequest.Marshal(b, m, deterministic)
}
func (m *ListApplicationProfilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListApplicationProfilesRequest.Merge(m, src)
}
func (m *ListApplicationProfilesRequest) XXX_Size() int {
	return xxx_messageInfo_ListApplicationProfilesRequest.Size(m)
}
func (m *ListApplicationProfilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListApplicationProfilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListApplicationProfilesRequest proto.InternalMessageInfo

func (m *ListApplicationProfilesRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ListApplicationProfilesRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListApplicationProfilesRequest) GetCont() string {
	if m != nil {
		return m.Cont
	}
	return ""
}

func (m *ListApplicationProfilesRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *ListApplicationProfilesRequest) GetCloudAccountIdentifier() string {
	if m != nil {
		return m.CloudAccountIdentifier
	}
	return ""
}

// ListApplicationProfilesResponse contains the list of ApplicationProfiles (with nil Spec)
type ListApplicationProfilesResponse struct {
	// Success indicates if the list was successfully retrieved
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if the operation failed
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Error code for programmatic error handling
	ErrorCode ErrorCode `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=storageserver.v1.ErrorCode" json:"error_code,omitempty"`
	// ApplicationProfiles list (Spec will be nil for each item)
	ApplicationProfiles []*v1beta1.ApplicationProfile `protobuf:"bytes,4,rep,name=application_profiles,json=applicationProfiles,proto3" json:"application_profiles,omitempty"`
	// Continue token for next page (empty if no more results)
	Cont                 string   `protobuf:"bytes,5,opt,name=cont,proto3" json:"cont,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListApplicationProfilesResponse) Reset()         { *m = ListApplicationProfilesResponse{} }
func (m *ListApplicationProfilesResponse) String() string { return proto.CompactTextString(m) }
func (*ListApplicationProfilesResponse) ProtoMessage()    {}
func (*ListApplicationProfilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{5}
}
func (m *ListApplicationProfilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListApplicationProfilesResponse.Unmarshal(m, b)
}
func (m *ListApplicationProfilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListApplicationProfilesResponse.Marshal(b, m, deterministic)
}
func (m *ListApplicationProfilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListApplicationProfilesResponse.Merge(m, src)
}
func (m *ListApplicationProfilesResponse) XXX_Size() int {
	return xxx_messageInfo_ListApplicationProfilesResponse.Size(m)
}
func (m *ListApplicationProfilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListApplicationProfilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListApplicationProfilesResponse proto.InternalMessageInfo

func (m *ListApplicationProfilesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ListApplicationProfilesResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *ListApplicationProfilesResponse) GetErrorCode() ErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (m *ListApplicationProfilesResponse) GetApplicationProfiles() []*v1beta1.ApplicationProfile {
	if m != nil {
		return m.ApplicationProfiles
	}
	return nil
}

func (m *ListApplicationProfilesResponse) GetCont() string {
	if m != nil {
		return m.Cont
	}
	return ""
}

// ListNetworkNeighborhoodsRequest requests a list of NetworkNeighborhoods in a namespace
// customer_guid, cluster, host_type, and host_id are sent via gRPC metadata headers
type ListNetworkNeighborhoodsRequest struct {
	// Namespace to list neighborhoods from
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Limit number of items to return (0 means server default)
	Limit int64 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	// Continue token for pagination
	Cont string `protobuf:"bytes,5,opt,name=cont,proto3" json:"cont,omitempty"`
	// Region of the resource (non-k8s scope identifier, e.g. "us-east-1")
	Region string `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	// CloudAccountIdentifier of the resource (non-k8s scope identifier, e.g. AWS account ID "123456789012", GCP project ID)
	CloudAccountIdentifier string   `protobuf:"bytes,7,opt,name=cloud_account_identifier,json=cloudAccountIdentifier,proto3" json:"cloud_account_identifier,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *ListNetworkNeighborhoodsRequest) Reset()         { *m = ListNetworkNeighborhoodsRequest{} }
func (m *ListNetworkNeighborhoodsRequest) String() string { return proto.CompactTextString(m) }
func (*ListNetworkNeighborhoodsRequest) ProtoMessage()    {}
func (*ListNetworkNeighborhoodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{6}
}
func (m *ListNetworkNeighborhoodsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNetworkNeighborhoodsRequest.Unmarshal(m, b)
}
func (m *ListNetworkNeighborhoodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNetworkNeighborhoodsRequest.Marshal(b, m, deterministic)
}
func (m *ListNetworkNeighborhoodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNetworkNeighborhoodsRequest.Merge(m, src)
}
func (m *ListNetworkNeighborhoodsRequest) XXX_Size() int {
	return xxx_messageInfo_ListNetworkNeighborhoodsRequest.Size(m)
}
func (m *ListNetworkNeighborhoodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNetworkNeighborhoodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListNetworkNeighborhoodsRequest proto.InternalMessageInfo

func (m *ListNetworkNeighborhoodsRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ListNetworkNeighborhoodsRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListNetworkNeighborhoodsRequest) GetCont() string {
	if m != nil {
		return m.Cont
	}
	return ""
}

func (m *ListNetworkNeighborhoodsRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *ListNetworkNeighborhoodsRequest) GetCloudAccountIdentifier() string {
	if m != nil {
		return m.CloudAccountIdentifier
	}
	return ""
}

// ListNetworkNeighborhoodsResponse contains the list of NetworkNeighborhoods (with nil Spec)
type ListNetworkNeighborhoodsResponse struct {
	// Success indicates if the list was successfully retrieved
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if the operation failed
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Error code for programmatic error handling
	ErrorCode ErrorCode `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=storageserver.v1.ErrorCode" json:"error_code,omitempty"`
	// NetworkNeighborhoods list (Spec will be nil for each item)
	NetworkNeighborhoods []*v1beta1.NetworkNeighborhood `protobuf:"bytes,4,rep,name=network_neighborhoods,json=networkNeighborhoods,proto3" json:"network_neighborhoods,omitempty"`
	// Continue token for next page (empty if no more results)
	Cont                 string   `protobuf:"bytes,5,opt,name=cont,proto3" json:"cont,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListNetworkNeighborhoodsResponse) Reset()         { *m = ListNetworkNeighborhoodsResponse{} }
func (m *ListNetworkNeighborhoodsResponse) String() string { return proto.CompactTextString(m) }
func (*ListNetworkNeighborhoodsResponse) ProtoMessage()    {}
func (*ListNetworkNeighborhoodsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{7}
}
func (m *ListNetworkNeighborhoodsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNetworkNeighborhoodsResponse.Unmarshal(m, b)
}
func (m *ListNetworkNeighborhoodsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNetworkNeighborhoodsResponse.Marshal(b, m, deterministic)
}
func (m *ListNetworkNeighborhoodsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNetworkNeighborhoodsResponse.Merge(m, src)
}
func (m *ListNetworkNeighborhoodsResponse) XXX_Size() int {
	return xxx_messageInfo_ListNetworkNeighborhoodsResponse.Size(m)
}
func (m *ListNetworkNeighborhoodsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNetworkNeighborhoodsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListNetworkNeighborhoodsResponse proto.InternalMessageInfo

func (m *ListNetworkNeighborhoodsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ListNetworkNeighborhoodsResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *ListNetworkNeighborhoodsResponse) GetErrorCode() ErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (m *ListNetworkNeighborhoodsResponse) GetNetworkNeighborhoods() []*v1beta1.NetworkNeighborhood {
	if m != nil {
		return m.NetworkNeighborhoods
	}
	return nil
}

func (m *ListNetworkNeighborhoodsResponse) GetCont() string {
	if m != nil {
		return m.Cont
	}
	return ""
}

// PutSBOMRequest uploads an SBOM blob plus the keys identifying it.
// customer_guid, cluster, host_type, and host_id are sent via gRPC metadata
// headers (see the AuthInterceptor on the server side). The unary path is
// intended for SBOMs up to ~4 MiB; use PutSBOMStream for larger payloads.
type PutSBOMRequest struct {
	// image_digest is the SHA-256 digest of the scanned image (without the
	// "sha256:" prefix). Part of the primary key.
	ImageDigest string `protobuf:"bytes,1,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	// syft_version is the version of syft that produced the blob. Part of the
	// primary key — multiple syft versions can coexist for one
	// (customer_guid, image_digest) during gradual fleet upgrades.
	SyftVersion string `protobuf:"bytes,2,opt,name=syft_version,json=syftVersion,proto3" json:"syft_version,omitempty"`
	// source identifies how this SBOM was produced.
	Source SBOMSource `protobuf:"varint,3,opt,name=source,proto3,enum=storageserver.v1.SBOMSource" json:"source,omitempty"`
	// sbom is the SBOM payload as a SBOMSyft K8s resource (the same shape
	// produced by syft + v1beta1.StripSBOM in node-agent / kubevuln).
	Sbom                 *v1beta1.SBOMSyft `protobuf:"bytes,4,opt,name=sbom,proto3" json:"sbom,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PutSBOMRequest) Reset()         { *m = PutSBOMRequest{} }
func (m *PutSBOMRequest) String() string { return proto.CompactTextString(m) }
func (*PutSBOMRequest) ProtoMessage()    {}
func (*PutSBOMRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{8}
}
func (m *PutSBOMRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutSBOMRequest.Unmarshal(m, b)
}
func (m *PutSBOMRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutSBOMRequest.Marshal(b, m, deterministic)
}
func (m *PutSBOMRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutSBOMRequest.Merge(m, src)
}
func (m *PutSBOMRequest) XXX_Size() int {
	return xxx_messageInfo_PutSBOMRequest.Size(m)
}
func (m *PutSBOMRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutSBOMRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutSBOMRequest proto.InternalMessageInfo

func (m *PutSBOMRequest) GetImageDigest() string {
	if m != nil {
		return m.ImageDigest
	}
	return ""
}

func (m *PutSBOMRequest) GetSyftVersion() string {
	if m != nil {
		return m.SyftVersion
	}
	return ""
}

func (m *PutSBOMRequest) GetSource() SBOMSource {
	if m != nil {
		return m.Source
	}
	return SBOMSource_SBOM_SOURCE_UNSPECIFIED
}

func (m *PutSBOMRequest) GetSbom() *v1beta1.SBOMSyft {
	if m != nil {
		return m.Sbom
	}
	return nil
}

// PutSBOMResponse indicates success or failure of the operation. S3 +
// Postgres persistence happens asynchronously via Pulsar; success here
// means the upload was accepted and the Pulsar message was published.
type PutSBOMResponse struct {
	Success              bool      `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage         string    `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorCode            ErrorCode `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=storageserver.v1.ErrorCode" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PutSBOMResponse) Reset()         { *m = PutSBOMResponse{} }
func (m *PutSBOMResponse) String() string { return proto.CompactTextString(m) }
func (*PutSBOMResponse) ProtoMessage()    {}
func (*PutSBOMResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{9}
}
func (m *PutSBOMResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutSBOMResponse.Unmarshal(m, b)
}
func (m *PutSBOMResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutSBOMResponse.Marshal(b, m, deterministic)
}
func (m *PutSBOMResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutSBOMResponse.Merge(m, src)
}
func (m *PutSBOMResponse) XXX_Size() int {
	return xxx_messageInfo_PutSBOMResponse.Size(m)
}
func (m *PutSBOMResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutSBOMResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutSBOMResponse proto.InternalMessageInfo

func (m *PutSBOMResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PutSBOMResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *PutSBOMResponse) GetErrorCode() ErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

// PutSBOMChunk is a single chunk of a streamed SBOM upload. The first
// chunk in the stream MUST set metadata. Subsequent chunks set only
// blob_chunk. Concatenated blob_chunk values form the serialized SBOMSyft
// proto payload.
type PutSBOMChunk struct {
	// metadata is set on the first chunk only.
	Metadata *PutSBOMChunkMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// blob_chunk is a slice of the serialized SBOMSyft payload.
	BlobChunk            []byte   `protobuf:"bytes,2,opt,name=blob_chunk,json=blobChunk,proto3" json:"blob_chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutSBOMChunk) Reset()         { *m = PutSBOMChunk{} }
func (m *PutSBOMChunk) String() string { return proto.CompactTextString(m) }
func (*PutSBOMChunk) ProtoMessage()    {}
func (*PutSBOMChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{10}
}
func (m *PutSBOMChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutSBOMChunk.Unmarshal(m, b)
}
func (m *PutSBOMChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutSBOMChunk.Marshal(b, m, deterministic)
}
func (m *PutSBOMChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutSBOMChunk.Merge(m, src)
}
func (m *PutSBOMChunk) XXX_Size() int {
	return xxx_messageInfo_PutSBOMChunk.Size(m)
}
func (m *PutSBOMChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_PutSBOMChunk.DiscardUnknown(m)
}

var xxx_messageInfo_PutSBOMChunk proto.InternalMessageInfo

func (m *PutSBOMChunk) GetMetadata() *PutSBOMChunkMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *PutSBOMChunk) GetBlobChunk() []byte {
	if m != nil {
		return m.BlobChunk
	}
	return nil
}

// PutSBOMChunkMetadata is the metadata header sent on the first chunk of a
// PutSBOMStream call.
type PutSBOMChunkMetadata struct {
	ImageDigest          string     `protobuf:"bytes,1,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	SyftVersion          string     `protobuf:"bytes,2,opt,name=syft_version,json=syftVersion,proto3" json:"syft_version,omitempty"`
	Source               SBOMSource `protobuf:"varint,3,opt,name=source,proto3,enum=storageserver.v1.SBOMSource" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PutSBOMChunkMetadata) Reset()         { *m = PutSBOMChunkMetadata{} }
func (m *PutSBOMChunkMetadata) String() string { return proto.CompactTextString(m) }
func (*PutSBOMChunkMetadata) ProtoMessage()    {}
func (*PutSBOMChunkMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{11}
}
func (m *PutSBOMChunkMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutSBOMChunkMetadata.Unmarshal(m, b)
}
func (m *PutSBOMChunkMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutSBOMChunkMetadata.Marshal(b, m, deterministic)
}
func (m *PutSBOMChunkMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutSBOMChunkMetadata.Merge(m, src)
}
func (m *PutSBOMChunkMetadata) XXX_Size() int {
	return xxx_messageInfo_PutSBOMChunkMetadata.Size(m)
}
func (m *PutSBOMChunkMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_PutSBOMChunkMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_PutSBOMChunkMetadata proto.InternalMessageInfo

func (m *PutSBOMChunkMetadata) GetImageDigest() string {
	if m != nil {
		return m.ImageDigest
	}
	return ""
}

func (m *PutSBOMChunkMetadata) GetSyftVersion() string {
	if m != nil {
		return m.SyftVersion
	}
	return ""
}

func (m *PutSBOMChunkMetadata) GetSource() SBOMSource {
	if m != nil {
		return m.Source
	}
	return SBOMSource_SBOM_SOURCE_UNSPECIFIED
}

// GetSBOMRequest probes for or fetches an SBOM by primary key.
// customer_guid is sent via gRPC metadata headers.
type GetSBOMRequest struct {
	// image_digest is the SHA-256 digest of the requested image (without the
	// "sha256:" prefix).
	ImageDigest string `protobuf:"bytes,1,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	// syft_version is the syft version that produced the requested SBOM. The
	// (image_digest, syft_version) pair is the lookup key. Leave empty to
	// request "latest available version" semantics; the server returns the
	// most recently created SBOM for the image.
	SyftVersion string `protobuf:"bytes,2,opt,name=syft_version,json=syftVersion,proto3" json:"syft_version,omitempty"`
	// metadata_only skips the blob and returns only SBOMMetadata. Used by
	// agents to decide whether to regenerate.
	MetadataOnly         bool     `protobuf:"varint,3,opt,name=metadata_only,json=metadataOnly,proto3" json:"metadata_only,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSBOMRequest) Reset()         { *m = GetSBOMRequest{} }
func (m *GetSBOMRequest) String() string { return proto.CompactTextString(m) }
func (*GetSBOMRequest) ProtoMessage()    {}
func (*GetSBOMRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{12}
}
func (m *GetSBOMRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSBOMRequest.Unmarshal(m, b)
}
func (m *GetSBOMRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSBOMRequest.Marshal(b, m, deterministic)
}
func (m *GetSBOMRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSBOMRequest.Merge(m, src)
}
func (m *GetSBOMRequest) XXX_Size() int {
	return xxx_messageInfo_GetSBOMRequest.Size(m)
}
func (m *GetSBOMRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSBOMRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSBOMRequest proto.InternalMessageInfo

func (m *GetSBOMRequest) GetImageDigest() string {
	if m != nil {
		return m.ImageDigest
	}
	return ""
}

func (m *GetSBOMRequest) GetSyftVersion() string {
	if m != nil {
		return m.SyftVersion
	}
	return ""
}

func (m *GetSBOMRequest) GetMetadataOnly() bool {
	if m != nil {
		return m.MetadataOnly
	}
	return false
}

// GetSBOMResponse returns the SBOM (or just metadata).
type GetSBOMResponse struct {
	Success      bool      `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string    `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorCode    ErrorCode `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=storageserver.v1.ErrorCode" json:"error_code,omitempty"`
	// exists indicates whether an SBOM row was found for the requested key.
	// When false, success is still true and metadata + sbom are empty.
	Exists bool `protobuf:"varint,4,opt,name=exists,proto3" json:"exists,omitempty"`
	// metadata is populated whenever exists=true.
	Metadata *SBOMMetadata `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// sbom is populated only when exists=true and metadata_only was false on
	// the request.
	Sbom                 *v1beta1.SBOMSyft `protobuf:"bytes,6,opt,name=sbom,proto3" json:"sbom,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetSBOMResponse) Reset()         { *m = GetSBOMResponse{} }
func (m *GetSBOMResponse) String() string { return proto.CompactTextString(m) }
func (*GetSBOMResponse) ProtoMessage()    {}
func (*GetSBOMResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{13}
}
func (m *GetSBOMResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSBOMResponse.Unmarshal(m, b)
}
func (m *GetSBOMResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSBOMResponse.Marshal(b, m, deterministic)
}
func (m *GetSBOMResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSBOMResponse.Merge(m, src)
}
func (m *GetSBOMResponse) XXX_Size() int {
	return xxx_messageInfo_GetSBOMResponse.Size(m)
}
func (m *GetSBOMResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSBOMResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSBOMResponse proto.InternalMessageInfo

func (m *GetSBOMResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetSBOMResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetSBOMResponse) GetErrorCode() ErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (m *GetSBOMResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func (m *GetSBOMResponse) GetMetadata() *SBOMMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *GetSBOMResponse) GetSbom() *v1beta1.SBOMSyft {
	if m != nil {
		return m.Sbom
	}
	return nil
}

// GetSBOMChunk is a single chunk of a streamed SBOM download. The first
// chunk sets metadata + status; subsequent chunks set only blob_chunk.
type GetSBOMChunk struct {
	// metadata is set on the first chunk only.
	Metadata *GetSBOMChunkMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// blob_chunk is a slice of the serialized SBOMSyft payload.
	BlobChunk            []byte   `protobuf:"bytes,2,opt,name=blob_chunk,json=blobChunk,proto3" json:"blob_chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSBOMChunk) Reset()         { *m = GetSBOMChunk{} }
func (m *GetSBOMChunk) String() string { return proto.CompactTextString(m) }
func (*GetSBOMChunk) ProtoMessage()    {}
func (*GetSBOMChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{14}
}
func (m *GetSBOMChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSBOMChunk.Unmarshal(m, b)
}
func (m *GetSBOMChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSBOMChunk.Marshal(b, m, deterministic)
}
func (m *GetSBOMChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSBOMChunk.Merge(m, src)
}
func (m *GetSBOMChunk) XXX_Size() int {
	return xxx_messageInfo_GetSBOMChunk.Size(m)
}
func (m *GetSBOMChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSBOMChunk.DiscardUnknown(m)
}

var xxx_messageInfo_GetSBOMChunk proto.InternalMessageInfo

func (m *GetSBOMChunk) GetMetadata() *GetSBOMChunkMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *GetSBOMChunk) GetBlobChunk() []byte {
	if m != nil {
		return m.BlobChunk
	}
	return nil
}

// GetSBOMChunkMetadata is the status header sent on the first chunk of a
// GetSBOMStream call. If exists=false or success=false the server closes
// the stream without sending blob chunks.
type GetSBOMChunkMetadata struct {
	Success              bool          `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage         string        `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorCode            ErrorCode     `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=storageserver.v1.ErrorCode" json:"error_code,omitempty"`
	Exists               bool          `protobuf:"varint,4,opt,name=exists,proto3" json:"exists,omitempty"`
	SbomMetadata         *SBOMMetadata `protobuf:"bytes,5,opt,name=sbom_metadata,json=sbomMetadata,proto3" json:"sbom_metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetSBOMChunkMetadata) Reset()         { *m = GetSBOMChunkMetadata{} }
func (m *GetSBOMChunkMetadata) String() string { return proto.CompactTextString(m) }
func (*GetSBOMChunkMetadata) ProtoMessage()    {}
func (*GetSBOMChunkMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{15}
}
func (m *GetSBOMChunkMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSBOMChunkMetadata.Unmarshal(m, b)
}
func (m *GetSBOMChunkMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSBOMChunkMetadata.Marshal(b, m, deterministic)
}
func (m *GetSBOMChunkMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSBOMChunkMetadata.Merge(m, src)
}
func (m *GetSBOMChunkMetadata) XXX_Size() int {
	return xxx_messageInfo_GetSBOMChunkMetadata.Size(m)
}
func (m *GetSBOMChunkMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSBOMChunkMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_GetSBOMChunkMetadata proto.InternalMessageInfo

func (m *GetSBOMChunkMetadata) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetSBOMChunkMetadata) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetSBOMChunkMetadata) GetErrorCode() ErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (m *GetSBOMChunkMetadata) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func (m *GetSBOMChunkMetadata) GetSbomMetadata() *SBOMMetadata {
	if m != nil {
		return m.SbomMetadata
	}
	return nil
}

// SBOMMetadata is the indexed view of an SBOM row, returned by GetSBOM
// with or without metadata_only=true.
type SBOMMetadata struct {
	// image_digest of the scanned image (without the "sha256:" prefix).
	ImageDigest string `protobuf:"bytes,1,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	// syft_version that produced the SBOM blob.
	SyftVersion string `protobuf:"bytes,2,opt,name=syft_version,json=syftVersion,proto3" json:"syft_version,omitempty"`
	// source identifies how this SBOM was produced.
	Source SBOMSource `protobuf:"varint,3,opt,name=source,proto3,enum=storageserver.v1.SBOMSource" json:"source,omitempty"`
	// blob_size_bytes is the size of the SBOM blob in S3.
	BlobSizeBytes int64 `protobuf:"varint,4,opt,name=blob_size_bytes,json=blobSizeBytes,proto3" json:"blob_size_bytes,omitempty"`
	// created_at is the RFC3339 timestamp when the row was first inserted.
	CreatedAt string `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// last_referenced_at is the RFC3339 timestamp when the orchestrator most
	// recently resolved an inventory entry to this SBOM. Drives eviction.
	LastReferencedAt     string   `protobuf:"bytes,6,opt,name=last_referenced_at,json=lastReferencedAt,proto3" json:"last_referenced_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SBOMMetadata) Reset()         { *m = SBOMMetadata{} }
func (m *SBOMMetadata) String() string { return proto.CompactTextString(m) }
func (*SBOMMetadata) ProtoMessage()    {}
func (*SBOMMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d90829bc66d9c54, []int{16}
}
func (m *SBOMMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SBOMMetadata.Unmarshal(m, b)
}
func (m *SBOMMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SBOMMetadata.Marshal(b, m, deterministic)
}
func (m *SBOMMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SBOMMetadata.Merge(m, src)
}
func (m *SBOMMetadata) XXX_Size() int {
	return xxx_messageInfo_SBOMMetadata.Size(m)
}
func (m *SBOMMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_SBOMMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_SBOMMetadata proto.InternalMessageInfo

func (m *SBOMMetadata) GetImageDigest() string {
	if m != nil {
		return m.ImageDigest
	}
	return ""
}

func (m *SBOMMetadata) GetSyftVersion() string {
	if m != nil {
		return m.SyftVersion
	}
	return ""
}

func (m *SBOMMetadata) GetSource() SBOMSource {
	if m != nil {
		return m.Source
	}
	return SBOMSource_SBOM_SOURCE_UNSPECIFIED
}

func (m *SBOMMetadata) GetBlobSizeBytes() int64 {
	if m != nil {
		return m.BlobSizeBytes
	}
	return 0
}

func (m *SBOMMetadata) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *SBOMMetadata) GetLastReferencedAt() string {
	if m != nil {
		return m.LastReferencedAt
	}
	return ""
}

func init() {
	proto.RegisterEnum("storageserver.v1.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterEnum("storageserver.v1.SBOMSource", SBOMSource_name, SBOMSource_value)
	proto.RegisterType((*SendContainerProfileRequest)(nil), "storageserver.v1.SendContainerProfileRequest")
	proto.RegisterType((*SendContainerProfileResponse)(nil), "storageserver.v1.SendContainerProfileResponse")
	proto.RegisterType((*GetProfileRequest)(nil), "storageserver.v1.GetProfileRequest")
	proto.RegisterType((*GetProfileResponse)(nil), "storageserver.v1.GetProfileResponse")
	proto.RegisterType((*ListApplicationProfilesRequest)(nil), "storageserver.v1.ListApplicationProfilesRequest")
	proto.RegisterType((*ListApplicationProfilesResponse)(nil), "storageserver.v1.ListApplicationProfilesResponse")
	proto.RegisterType((*ListNetworkNeighborhoodsRequest)(nil), "storageserver.v1.ListNetworkNeighborhoodsRequest")
	proto.RegisterType((*ListNetworkNeighborhoodsResponse)(nil), "storageserver.v1.ListNetworkNeighborhoodsResponse")
	proto.RegisterType((*PutSBOMRequest)(nil), "storageserver.v1.PutSBOMRequest")
	proto.RegisterType((*PutSBOMResponse)(nil), "storageserver.v1.PutSBOMResponse")
	proto.RegisterType((*PutSBOMChunk)(nil), "storageserver.v1.PutSBOMChunk")
	proto.RegisterType((*PutSBOMChunkMetadata)(nil), "storageserver.v1.PutSBOMChunkMetadata")
	proto.RegisterType((*GetSBOMRequest)(nil), "storageserver.v1.GetSBOMRequest")
	proto.RegisterType((*GetSBOMResponse)(nil), "storageserver.v1.GetSBOMResponse")
	proto.RegisterType((*GetSBOMChunk)(nil), "storageserver.v1.GetSBOMChunk")
	proto.RegisterType((*GetSBOMChunkMetadata)(nil), "storageserver.v1.GetSBOMChunkMetadata")
	proto.RegisterType((*SBOMMetadata)(nil), "storageserver.v1.SBOMMetadata")
}

func init() { proto.RegisterFile("storage_service.proto", fileDescriptor_3d90829bc66d9c54) }

var fileDescriptor_3d90829bc66d9c54 = []byte{
	// 1318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0x41, 0x73, 0xdb, 0x44,
	0x14, 0x46, 0x8e, 0xeb, 0xc4, 0x2f, 0x4e, 0xaa, 0x6e, 0xdd, 0xd4, 0xa4, 0x69, 0x70, 0x5d, 0xa6,
	0x93, 0xe9, 0x80, 0xdc, 0x04, 0x0e, 0x4c, 0x6f, 0x8e, 0xad, 0xa6, 0x9e, 0x3a, 0x56, 0xba, 0xb2,
	0xdb, 0xa1, 0x17, 0x8d, 0x2c, 0x6f, 0x1c, 0x8d, 0x6d, 0xc9, 0xd5, 0xae, 0x53, 0x52, 0x66, 0x18,
	0xb8, 0x30, 0x30, 0x70, 0xe2, 0xc6, 0x8d, 0x1b, 0x07, 0x0e, 0xdc, 0xe9, 0x81, 0x61, 0x86, 0xbf,
	0x03, 0x7f, 0x01, 0x46, 0xab, 0x95, 0xa3, 0xd8, 0xb2, 0x69, 0x66, 0x1a, 0x0c, 0x27, 0x6b, 0xbf,
	0xf7, 0xf6, 0xbd, 0xcf, 0xef, 0x7d, 0x5a, 0x3d, 0x09, 0xae, 0x51, 0xe6, 0x7a, 0x66, 0x87, 0x18,
	0x94, 0x78, 0xc7, 0xb6, 0x45, 0x94, 0x81, 0xe7, 0x32, 0x17, 0xc9, 0x02, 0xf6, 0x51, 0xe2, 0x29,
	0xc7, 0xdb, 0xeb, 0x8f, 0x3b, 0x36, 0x3b, 0x1a, 0xb6, 0x14, 0xcb, 0xed, 0x17, 0xbb, 0xc3, 0x16,
	0xa1, 0x96, 0x39, 0x20, 0x45, 0xe1, 0x56, 0x1c, 0x74, 0x3b, 0x45, 0x73, 0x60, 0xd3, 0x22, 0x75,
	0x0f, 0xd9, 0x0b, 0xd3, 0x23, 0x96, 0xdb, 0x1f, 0xb8, 0xd4, 0x66, 0xb6, 0xeb, 0x14, 0x8f, 0xb7,
	0x5b, 0x84, 0x99, 0xdb, 0xc5, 0x0e, 0x71, 0x88, 0x67, 0x32, 0xd2, 0x0e, 0x92, 0x14, 0x7e, 0x90,
	0xe0, 0x86, 0x4e, 0x9c, 0x76, 0xd9, 0x75, 0x98, 0x69, 0x3b, 0xc4, 0x3b, 0xf0, 0xdc, 0x43, 0xbb,
	0x47, 0x30, 0x79, 0x3e, 0x24, 0x94, 0xa1, 0xcf, 0x25, 0xb8, 0x62, 0x85, 0x36, 0x63, 0x10, 0x18,
	0x73, 0x52, 0x5e, 0xda, 0x5a, 0xde, 0xd1, 0x95, 0x53, 0x3e, 0xca, 0x88, 0x8f, 0x22, 0xf8, 0x28,
	0x83, 0x6e, 0x47, 0xf1, 0xf9, 0x28, 0x31, 0x7c, 0x14, 0xc1, 0x47, 0x99, 0xc8, 0x2b, 0x5b, 0x63,
	0x48, 0xe1, 0x7b, 0x09, 0x36, 0xe2, 0x29, 0xd2, 0x81, 0xeb, 0x50, 0x82, 0x72, 0xb0, 0x48, 0x87,
	0x96, 0x45, 0x28, 0xe5, 0xc4, 0x96, 0x70, 0xb8, 0x44, 0xb7, 0x61, 0x85, 0x78, 0x9e, 0xeb, 0x19,
	0x7d, 0x42, 0xa9, 0xd9, 0x21, 0xb9, 0x44, 0x5e, 0xda, 0x4a, 0xe3, 0x0c, 0x07, 0xf7, 0x03, 0x0c,
	0xdd, 0x07, 0x08, 0x9c, 0x2c, 0xb7, 0x4d, 0x72, 0x0b, 0x79, 0x69, 0x6b, 0x75, 0xe7, 0x86, 0x32,
	0x5e, 0x7c, 0x45, 0xf5, 0x7d, 0xca, 0x6e, 0x9b, 0xe0, 0x34, 0x09, 0x2f, 0x0b, 0x3f, 0x49, 0x70,
	0x65, 0x8f, 0xb0, 0xb1, 0xa2, 0x21, 0x48, 0x76, 0x6d, 0xa7, 0xcd, 0xd9, 0xa4, 0x31, 0xbf, 0x46,
	0x1b, 0x90, 0x76, 0xcc, 0x3e, 0xa1, 0x03, 0xd3, 0x0a, 0x69, 0x9c, 0x02, 0xfe, 0x0e, 0x7f, 0xc1,
	0xb3, 0xa7, 0x31, 0xbf, 0x46, 0x6b, 0x90, 0xf2, 0x48, 0xc7, 0x76, 0x9d, 0x5c, 0x92, 0xa3, 0x62,
	0x85, 0x3e, 0x82, 0x9c, 0xd5, 0x73, 0x87, 0x6d, 0xc3, 0xb4, 0x2c, 0x77, 0xe8, 0x30, 0xc3, 0x6e,
	0x13, 0x87, 0xd9, 0x87, 0x36, 0xf1, 0x72, 0x97, 0xb8, 0xe7, 0x1a, 0xb7, 0x97, 0x02, 0x73, 0x75,
	0x64, 0x2d, 0xfc, 0x98, 0x04, 0x14, 0x65, 0x3b, 0xf7, 0xfa, 0xa1, 0x2f, 0x25, 0xb8, 0x6a, 0x0e,
	0x06, 0x3d, 0xdb, 0x32, 0x7d, 0x59, 0x8c, 0x04, 0x96, 0xe4, 0x02, 0x6b, 0xbe, 0x01, 0x81, 0x95,
	0x4e, 0xa3, 0x87, 0xff, 0x1b, 0x99, 0x13, 0x18, 0xfa, 0x5a, 0x82, 0xac, 0x43, 0xd8, 0x0b, 0xd7,
	0xeb, 0x1a, 0x0e, 0xb1, 0x3b, 0x47, 0x2d, 0xd7, 0x3b, 0x72, 0xdd, 0x36, 0xaf, 0xe8, 0xf2, 0xce,
	0x93, 0x37, 0xc0, 0xa4, 0x1e, 0x84, 0xaf, 0x47, 0xa2, 0xe3, 0xab, 0xce, 0x24, 0x38, 0xe5, 0x9e,
	0x4b, 0xfd, 0x9b, 0xf7, 0xdc, 0x2f, 0x12, 0x6c, 0xd6, 0x6c, 0xca, 0x26, 0xab, 0x47, 0x43, 0x91,
	0x9f, 0x11, 0xb4, 0x34, 0x2e, 0xe8, 0x2c, 0x5c, 0xea, 0xd9, 0x7d, 0x9b, 0xf1, 0x4e, 0x2e, 0xe0,
	0x60, 0xe1, 0xcb, 0xdc, 0x4f, 0x25, 0x64, 0xca, 0xaf, 0x23, 0x32, 0x4f, 0xbd, 0xb6, 0xcc, 0x17,
	0x67, 0xca, 0xfc, 0x55, 0x02, 0xde, 0x99, 0x4a, 0x7e, 0xfe, 0x9a, 0xff, 0x4a, 0x82, 0x6c, 0x8c,
	0xe6, 0x69, 0x2e, 0x99, 0x5f, 0xb8, 0x38, 0xd1, 0x5f, 0x9d, 0x14, 0x3d, 0x8d, 0xeb, 0x47, 0xe1,
	0x95, 0x14, 0x54, 0x2f, 0x46, 0xae, 0xff, 0x83, 0xde, 0xff, 0x9a, 0x80, 0xfc, 0x74, 0xf6, 0xf3,
	0x6f, 0xfe, 0x37, 0x12, 0x5c, 0x8b, 0x3b, 0x67, 0xc2, 0xee, 0x5f, 0xd4, 0x41, 0x93, 0x8d, 0x39,
	0x68, 0xe2, 0xfb, 0xff, 0x87, 0x04, 0xab, 0x07, 0x43, 0xa6, 0xef, 0x6a, 0xfb, 0x61, 0xbb, 0x6f,
	0x41, 0xc6, 0xee, 0xfb, 0x03, 0x4a, 0xdb, 0xee, 0x10, 0xca, 0x44, 0xc7, 0x97, 0x39, 0x56, 0xe1,
	0x90, 0xef, 0x42, 0x4f, 0x0e, 0x99, 0x71, 0x4c, 0x3c, 0xea, 0xf7, 0x33, 0xa8, 0xdb, 0xb2, 0x8f,
	0x3d, 0x09, 0x20, 0xf4, 0x21, 0xa4, 0xa8, 0x3b, 0xf4, 0xac, 0xb0, 0x64, 0x1b, 0x93, 0x25, 0xf3,
	0x93, 0xea, 0xdc, 0x07, 0x0b, 0x5f, 0x64, 0x40, 0x92, 0xb6, 0xdc, 0xbe, 0x78, 0x22, 0x3c, 0x7a,
	0x03, 0xe5, 0xe1, 0x49, 0x4e, 0x0e, 0x19, 0xe6, 0x81, 0x0b, 0xdf, 0x4a, 0x70, 0x79, 0xf4, 0x7f,
	0xe7, 0x3f, 0x51, 0x3c, 0x87, 0x8c, 0x60, 0x53, 0x3e, 0x1a, 0x3a, 0x5d, 0xb4, 0x0b, 0x4b, 0x7d,
	0xc2, 0xcc, 0xb6, 0xc9, 0x4c, 0x31, 0x76, 0xdd, 0x99, 0x8c, 0x14, 0xdd, 0xb1, 0x2f, 0xbc, 0xf1,
	0x68, 0x1f, 0xba, 0x09, 0xd0, 0xea, 0xb9, 0x2d, 0xc3, 0xf2, 0xed, 0x9c, 0x71, 0x06, 0xa7, 0x7d,
	0x84, 0x6f, 0x28, 0x7c, 0x27, 0x41, 0x36, 0x2e, 0xc2, 0x3c, 0xfb, 0x5e, 0xf8, 0x14, 0x56, 0xf7,
	0xc8, 0x05, 0xa8, 0xf0, 0x36, 0xac, 0x84, 0x75, 0x31, 0x5c, 0xa7, 0x77, 0xc2, 0x49, 0x2d, 0xe1,
	0x4c, 0x08, 0x6a, 0x4e, 0xef, 0xa4, 0xf0, 0x5b, 0x02, 0x2e, 0x8f, 0xb2, 0xcf, 0xff, 0xd0, 0x58,
	0x83, 0x14, 0xf9, 0xc4, 0xa6, 0x8c, 0xf2, 0xbb, 0x60, 0x09, 0x8b, 0x15, 0xba, 0x1f, 0xd1, 0x46,
	0x30, 0xa7, 0x6c, 0xc6, 0xd7, 0x36, 0x46, 0x13, 0xe1, 0x7d, 0x95, 0xba, 0xa8, 0xfb, 0xea, 0x39,
	0x64, 0x44, 0x09, 0xcf, 0x21, 0xe4, 0xe8, 0x8e, 0xf3, 0x0b, 0xf9, 0x4f, 0x09, 0xb2, 0x71, 0x11,
	0xfe, 0x8b, 0xbd, 0x2b, 0xc3, 0x8a, 0x5f, 0x26, 0xe3, 0x9c, 0x0d, 0xcc, 0xf8, 0x9b, 0xc2, 0x55,
	0xe1, 0x2f, 0x09, 0x32, 0x51, 0xf3, 0x5c, 0x4f, 0xea, 0x3b, 0x70, 0x99, 0x37, 0x87, 0xda, 0x2f,
	0x89, 0xd1, 0x3a, 0x61, 0x84, 0x8a, 0x01, 0x60, 0xc5, 0x87, 0x75, 0xfb, 0x25, 0xd9, 0xf5, 0x41,
	0xbf, 0x89, 0x96, 0x47, 0xfc, 0x77, 0x50, 0xc3, 0x0c, 0x1f, 0x3d, 0x69, 0x81, 0x94, 0x18, 0x7a,
	0x0f, 0x50, 0xcf, 0xa4, 0xcc, 0xf0, 0xc8, 0x21, 0xf1, 0x88, 0x63, 0x05, 0x6e, 0xc1, 0x7c, 0x20,
	0xfb, 0x16, 0x3c, 0x32, 0x94, 0xd8, 0xdd, 0xdf, 0x13, 0x90, 0x1e, 0xd5, 0x1d, 0xad, 0xc3, 0x9a,
	0x8a, 0xb1, 0x86, 0x8d, 0xb2, 0x56, 0x51, 0x8d, 0x66, 0x5d, 0x3f, 0x50, 0xcb, 0xd5, 0x07, 0x55,
	0xb5, 0x22, 0xbf, 0x85, 0x36, 0x61, 0x3d, 0x62, 0xab, 0xd6, 0x9f, 0x94, 0x6a, 0xd5, 0x8a, 0x81,
	0xd5, 0xc7, 0x4d, 0x55, 0x6f, 0xc8, 0x12, 0xba, 0x01, 0xd7, 0xcf, 0xec, 0x2d, 0x35, 0x1b, 0x0f,
	0x35, 0x5c, 0x7d, 0xa6, 0x56, 0xe4, 0x04, 0xca, 0xc3, 0x46, 0xc4, 0x78, 0x80, 0xb5, 0x07, 0xd5,
	0x9a, 0x6a, 0x34, 0x34, 0xcd, 0xa8, 0x95, 0xf0, 0x9e, 0x2a, 0x2f, 0x4c, 0xf1, 0x28, 0x6b, 0xfb,
	0x07, 0x35, 0xb5, 0xa1, 0x56, 0xe4, 0xe4, 0x14, 0x8f, 0xba, 0xd6, 0x30, 0x1e, 0x68, 0xcd, 0x7a,
	0x45, 0xbe, 0x84, 0x6e, 0xc2, 0xdb, 0x67, 0x28, 0x36, 0x54, 0x5c, 0x2f, 0xd5, 0x0c, 0x8e, 0xc9,
	0xa9, 0x31, 0x86, 0x07, 0xcd, 0x9a, 0x5e, 0xc2, 0xc2, 0xb8, 0x38, 0xb6, 0xd7, 0x6f, 0x4f, 0x24,
	0xf4, 0x52, 0x9c, 0xf9, 0x94, 0x7d, 0xfa, 0x2e, 0x05, 0x38, 0xed, 0xa8, 0x9f, 0x88, 0x7b, 0xe8,
	0x5a, 0x13, 0x97, 0xc7, 0xeb, 0x98, 0x83, 0x6c, 0xd4, 0xf8, 0x54, 0xc3, 0x8f, 0x6a, 0x5a, 0xa9,
	0x22, 0x4b, 0xe3, 0x16, 0xac, 0xee, 0x55, 0xf5, 0x06, 0xfe, 0x58, 0x4e, 0xa0, 0x2c, 0xc8, 0x51,
	0xcb, 0x43, 0x4d, 0x6f, 0xc8, 0x0b, 0x3b, 0x3f, 0xa7, 0x60, 0x55, 0x0f, 0x84, 0xa5, 0x07, 0x5f,
	0x3e, 0xd0, 0x10, 0xb2, 0x71, 0xaf, 0xfa, 0xe8, 0xfd, 0x18, 0x05, 0x4e, 0xff, 0x6a, 0xb1, 0xae,
	0xbc, 0xae, 0xbb, 0x38, 0xdb, 0x9f, 0x02, 0x9c, 0xbe, 0x17, 0xa3, 0xdb, 0xb1, 0xe7, 0xd2, 0x58,
	0x8a, 0x77, 0x67, 0x3b, 0x89, 0xc0, 0x9f, 0xc1, 0xf5, 0x29, 0x6f, 0x22, 0xe8, 0xde, 0x64, 0x80,
	0xd9, 0x6f, 0x5c, 0xeb, 0xdb, 0xe7, 0xd8, 0x21, 0xf2, 0x7f, 0x21, 0x41, 0x6e, 0xda, 0x38, 0x8c,
	0xa6, 0xc4, 0x9b, 0x31, 0xf8, 0xaf, 0xef, 0x9c, 0x67, 0x8b, 0xe0, 0x50, 0x87, 0x45, 0x31, 0x5d,
	0xa0, 0xfc, 0xd4, 0xd1, 0x25, 0x4c, 0x70, 0x6b, 0x86, 0x87, 0x88, 0xd7, 0x80, 0x15, 0x01, 0xe9,
	0xcc, 0x23, 0x66, 0x1f, 0x6d, 0xce, 0x1e, 0x88, 0x5e, 0x23, 0xe6, 0x96, 0xe4, 0xb3, 0x14, 0x8f,
	0x8e, 0x38, 0x96, 0x67, 0x47, 0x91, 0xb8, 0x88, 0xe3, 0xe3, 0x82, 0x0e, 0x2b, 0x02, 0x12, 0x2c,
	0xff, 0x39, 0xea, 0xe6, 0xec, 0xe7, 0xe1, 0x3d, 0x69, 0x77, 0xe7, 0xd9, 0xbd, 0xd8, 0x4f, 0x80,
	0x2d, 0xd3, 0xea, 0x12, 0xa7, 0xcd, 0x3f, 0x01, 0x5a, 0x3d, 0x9b, 0x38, 0xac, 0x78, 0xbc, 0x5d,
	0xe4, 0x5f, 0xf8, 0x5a, 0x29, 0xfe, 0xf3, 0xc1, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x41,
	0xbc, 0x5a, 0x66, 0x14, 0x00, 0x00,
}
