apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: operatorcommands.kubescape.io
spec:
  group: kubescape.io
  names:
    plural: operatorcommands
    singular: operatorcommand
    kind: OperatorCommand
    shortNames:
      - opcmd
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                args:
                  type: object
                  additionalProperties: true
                commandType:
                  type: string
                designators:
                  type: array
                  items:
                    type: object
                    additionalProperties: true 
                guid:
                  type: string
            status:
              type: object
              properties:
                completed:
                  type: boolean
                completedAt:
                  type: string
                  format: date-time
                error:
                  type: object
                  properties:
                    errorCode:
                      type: integer
                    message:
                      type: string
                    reason:
                      type: string
                started:
                  type: boolean
                startedAt:
                  type: string
                  format: date-time
      subresources:
        status: {}
  conversion:
    strategy: None
